src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <picklist>
            <picklistValues>
                <fullName>Large Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Supply Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bakery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar/Tavern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty/Nail/Spa Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bicycle Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candy Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carwash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell Phone Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiropractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer and Software Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consignment/Second Hand Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenience Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dentist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drug and Vitamin Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drycleaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics/TV and Radio Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Covering Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <picklist>
            <picklistValues>
                <fullName>1st federal financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st First Source Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abanco INTERNATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC Global Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliant Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allied Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ameribank National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Credit Card Processing, Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAVINGS BANK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriMerchant Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMI-Merchant Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appstar Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic Stewardship Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVFUEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axia Corp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancard Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancfirst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BanCorpSouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankCard Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankcard USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banker&apos;s Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of America Merchant Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestPreQual_Ctrl.cls
@isTest 
private class TestPreQual_Ctrl  {
	
    static testMethod void preQual_UnitTest() {
    	
        Test.startTest(); 
        CALC.ApexTesting();
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusibess';
        insert testAccount;
        
        Campaign cmObj = new Campaign();
        cmObj.Name = 'Test';
        cmObj.Type = 'Internet';
        insert cmObj;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cmObj.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = testAccount.id;
        insert opp;
        
        preQual_Ctrl prq_ctrl = new preQual_Ctrl();
        prq_ctrl.doSave();
        CBRTesting_Ctrl cbrObj = new CBRTesting_Ctrl();
        cbrObj.doSave();
        //cbrObj.doCBRIntegration();
        
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        
        preQual_Ctrl preq_ctrl = new preQual_Ctrl();
        prq_ctrl.doSave();
        
        CBRTesting_Ctrl cbrtestObj = new CBRTesting_Ctrl();
        cbrObj.doSave();
       // cbrObj.doCBRIntegration();
        Test.stopTest(); 
    }
}