src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FederalTaxID__c</fullName>
        <label>Federal Tax ID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <label>Partners</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <picklist>
            <picklistValues>
                <fullName>1st federal financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st First Source Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abanco INTERNATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC Global Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliant Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allied Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ameribank National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Credit Card Processing, Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAVINGS BANK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriMerchant Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMI-Merchant Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appstar Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic Stewardship Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVFUEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axia Corp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancard Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancfirst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BanCorpSouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankCard Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankcard USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banker&apos;s Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of America Merchant Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System</description>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>QC in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Offer Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documents Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer Rescinded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted For Funding Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Additional Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Oppr_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Sold__c</fullName>
        <label>Amount Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Oppr_Offers</relationshipLabel>
        <relationshipName>Oppr_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Offered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Oppr_Offer</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oppr_Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Biz2CreditUtils.cls
public with sharing class Biz2CreditUtils {

	public static Account createAccount(Application app) {

		Account acct = new Account();

		acct.name = app.MerchantID;
		acct.BillingCity = app.BusinessCity;
		acct.FederalTaxID__c = app.FederalTaxId;

		//acct.c = Util.TestDate('20251212');
		//testAccount.Billing_End_Date__c = Util.TestDate('20251212');

		insert acct;
		return acct;
	}

	public static Contact createContact(Application app) {

		Contact con = new Contact();
		con.FirstName = app.FirstName;
		con.LastName = app.LastName;
		con.MailingCity = app.HomeCity;

		insert con;
		return con;
	}

	public static Opportunity createOpportunity(Application app) {

		Opportunity opp = new Opportunity();

		opp.External_ID__c = app.ExternalID;
		opp.Source_System__c = 'Biz2Credit';
		opp.Status__c = 'Processing';
		opp.Status_Reason__c = 'Passed';
		opp.Name = app.ExternalID;
		opp.StageName = 'Prospecting';
		opp.CloseDate = system.today();

		insert opp;
		return opp;
	}

	public static Date dateConversion(String conDate) {

		Integer year = Integer.valueOf(conDate.substring(0, 4));
		Integer month = Integer.valueOf(conDate.substring(4, 6));
		Integer day = Integer.valueOf(conDate.substring(6, 8));

		System.debug('year....' + year + '....month...' + month + '..day..' + day);
		Date d;
		try {
			d = Date.newInstance(year, month, day);
		} 
		catch (Exception e) {
			return null;
		}

		return d;
	}

	public static String getInstanceURL() {
		// code for fetch server
		String sfdcUrl;
		String sasf = URL.getSalesforceBaseUrl().getHost();
		Integer endpoint = 0;
		endpoint = sasf.indexOf('.visual.force.');

		Integer startpoint = 0;
		startpoint = sasf.indexOf('.');
		System.debug('endpoint.......' + endpoint + '...........startpoint..' + startpoint);
		if (endpoint >= 0 && startpoint >= 0) {
			sfdcUrl = 'https://' + sasf.substring(startpoint + 1, endpoint) + '.salesforce.com';
		}
		System.debug('sfdcUrl....' + sfdcUrl);
		System.debug('sasf....' + sasf);

		return sasf;
	}

	public static Campaign createCampaign() {
		
		Campaign cam = new Campaign();
		cam.Name = 'testCom';
		cam.type = 'partners';
		insert cam;
		return cam;
	}
	public static Opportunity createOpportunity() {
		
		Opportunity opp = new Opportunity();
		opp.Name = 'testOp1';
		opp.LeadSource = 'A001';
		opp.Campaign = Biz2CreditUtils.createCampaign();
		opp.CloseDate = System.today();
		opp.StageName = 'Approved';
		opp.External_ID__c = '123456';
		opp.Status__c = 'Contract Available';
		opp.Source_System__c = 'Biz2Credit';
		opp.Current_Processor__c = 'ABC Global System';
		insert opp;
		return opp;
	}
	
	public static Opportunity createOpportunity_new() {
		
		Opportunity opp = new Opportunity();
		opp.Name = 'testOp1';
		opp.LeadSource = 'A001';
		opp.Campaign = Biz2CreditUtils.createCampaign();
		opp.CloseDate = System.today();
		opp.StageName = 'Approved';
		opp.External_ID__c = '' + System.currentTimeMillis();
		opp.Status__c = 'Contract NOT Available';
		opp.Source_System__c = 'B2C';
		opp.Current_Processor__c = 'ABC Global System';
		insert opp;
		return opp;
	}

	public static Oppr_Document__c createOppDoc(Opportunity opp) {
		
		Oppr_Document__c OppDoc = new Oppr_Document__c();
		OppDoc.Document_Name__c = 'testDoc';
		OppDoc.Additional_Notes__c = 'testDoc';
		OppDoc.Opportunity__c = opp.Id;
		insert OppDoc;
		return OppDoc;
	}
	
	public static Attachment createAttachment(Oppr_Document__c oppDoc) {
		
		Attachment attachment = new Attachment();
		attachment.Body = Blob.valueOf('This is Test.');
		attachment.Name = String.valueOf('test.txt');
		attachment.ParentId = oppDoc.Id;
		insert attachment;
		return attachment;
	}

	public static Oppr_Offer__c createOpprOffer(String oppID) {
		
		Oppr_Offer__c opprOffer = new Oppr_Offer__c();
		opprOffer.Amount__c = 123;
		opprOffer.Amount_Sold__c = 12;
		opprOffer.Opportunity__c = oppID;
		insert opprOffer;
		Oppr_Offer__c oppr = [SELECT id, Status__c, Name FROM Oppr_Offer__c WHERE Id = : opprOffer.id LIMIT 1];
		update oppr;
		return oppr;
	}

}