src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Site_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Site Surveys</relationshipLabel>
        <relationshipName>R00N70000001wK6gEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Survey_Type__c</fullName>
        <label>Site Survey Type</label>
        <picklist>
            <picklistValues>
                <fullName>Merchant Site 72</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchant Term 72</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mystery Shopper 72</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchant Site 48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchant Term 48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mystery Shopper 48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchant Site 24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchant Term 24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mystery Shopper 24</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Site Survey</label>
    <nameField>
        <label>Site Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSiteSurveys_Ctrl.cls
@isTest 
private class TestSiteSurveys_Ctrl {

    static testMethod void SiteSurveys_UnitTest() {
    
        Test.startTest();
        CALC.ApexTesting(); 
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm);

        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        
        Site_Survey__c siteObj = new  Site_Survey__c();
        siteObj.Name = 'xyz';
        siteObj.Site_Survey_Type__c = 'Merchant Site 72';
        siteObj.Opportunity__c = opp.Id;
        insert  siteObj;       
        ApexPages.currentPage().getParameters().put('Id', siteObj.Id);
        ApexPages.StandardController siteController = new ApexPages.standardController(siteObj);
        SiteSurveys_Ctrl siteS = new SiteSurveys_Ctrl(siteController);
       
        siteS.Save();
        siteS.cancel();
        
        Test.stopTest();
    }
    
     static testMethod void SiteSurveys_UnitTest1() {
     
        Test.startTest(); 
        CALC.ApexTesting();
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm);
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        ApexPages.currentPage().getParameters().put('retURL', 'oppId=');
        Site_Survey__c siteObj = new  Site_Survey__c();
        siteObj.Name = 'xyz';
        siteObj.Site_Survey_Type__c = 'Merchant Site 72';
        siteObj.Opportunity__c = opp.Id;
      //  insert  siteObj;       
        
        ApexPages.currentPage().getParameters().put('Id', null);        
        ApexPages.StandardController siteController = new ApexPages.standardController(siteObj);
        SiteSurveys_Ctrl siteS = new SiteSurveys_Ctrl(siteController);
       
        siteS.Save();
        siteS.cancel();
        
        Test.stopTest();
    }
    
    static testMethod void SiteSurveys_UnitTest2() {
        
        Test.startTest();
        CALC.ApexTesting(); 
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm);
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        ApexPages.currentPage().getParameters().put('retURL', 'testId');
        Site_Survey__c siteObj = new  Site_Survey__c();
        siteObj.Name = 'xyz';
        siteObj.Site_Survey_Type__c = 'Merchant Site 72';
        siteObj.Opportunity__c = opp.Id;
      //  insert  siteObj;       
        
        ApexPages.currentPage().getParameters().put('Id', null);        
        ApexPages.StandardController siteController = new ApexPages.standardController(siteObj);
        SiteSurveys_Ctrl siteS = new SiteSurveys_Ctrl(siteController);
       
        siteS.Save();
        siteS.cancel();
        
        Test.stopTest();
    } 
}