src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <picklist>
            <picklistValues>
                <fullName>1st federal financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st First Source Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abanco INTERNATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC Global Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliant Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allied Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ameribank National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Credit Card Processing, Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAVINGS BANK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriMerchant Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMI-Merchant Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appstar Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic Stewardship Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVFUEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axia Corp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancard Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancfirst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BanCorpSouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankCard Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankcard USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banker&apos;s Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of America Merchant Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>QC in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Offer Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documents Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer Rescinded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted For Funding Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RequiredDoc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RequiredDoc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSubmitApplication.cls
@istest

public class TestSubmitApplication
{
    static testMethod void testDoPost() {
        
        Test.startTest();
        CALC.ApexTesting();
        Application app = new Application();

        // Using unique identifier of source system for Acct and opportunity Name
        //Get List Of required fields - contact     
        app.FirstName = 'James';
        app.LastName = 'Jones';
        app.HomeCity = 'Washington';
        app.LegalBusName = 'Test Business Merchant';

        //Get List Of required fields - account
        app.BusinessCity = 'Washington DC';
        app.FederalTaxId = '111155555';

        //Get List Of required fields - opportunity
        app.AvgMonthSales = 50000;
        app.MajorCreditCardsProc = 'Visa';
        app.AvgMonthTrans = 45000;
        app.CCSalesLastMonth = 100000;
        app.CCSalesLast1Month = 45000;
        app.CCSalesLast2Month = 55000;
        app.CCSalesLast3Month = 65000;
        app.NumOfTransLastMonth = 300;
        app.NumOfTrans1Month = 250;
        app.NumOfTrans2Month = 350;
        app.NumOfTrans3Month = 450;
        app.SourceSystem = 'Biz2Credit';
        app.ExternalID = 'ExtID 10001';
        app.MerchantID = 'Merchant 2000';

        app.Product = 'ACH';
        app.BusinessZip = '20716';
        app.AgeOfBusinessYrs = '20130404';

        app.HomeZip = '20716';
        app.DateOfBirth = '20130404';

        app.CloseDate = '20130404';

        app.HomeState = 'MD';
        app.ResidenceStatus = 'Yes';

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.addHeader('Content-Type', 'application/x-www-form-urlencoded');
        
        Application app2 = new Application();

        // Using unique identifier of source system for Acct and opportunity Name
        //Get List Of required fields - contact     
        app2.FirstName = 'James2';
        app2.LastName = 'Jone2s';
        app2.HomeCity = 'Washington2';
        app2.LegalBusName = 'Test Business Merchant2';

        //Get List Of required fields - account
        app2.BusinessCity = 'Washington DC';
        app2.FederalTaxId = '111165555';

        //Get List Of required fields - opportunity
        app2.AvgMonthSales = 50000;
        app2.MajorCreditCardsProc = 'Visa';
        app2.AvgMonthTrans = 45000;
        app2.CCSalesLastMonth = 100000;
        app2.CCSalesLast1Month = 45000;
        app2.CCSalesLast2Month = 55000;
        app2.CCSalesLast3Month = 65000;
        app2.NumOfTransLastMonth = 300;
        app2.NumOfTrans1Month = 250;
        app2.NumOfTrans2Month = 350;
        app2.NumOfTrans3Month = 450;
        app2.SourceSystem = 'Biz2Credit';
        app2.ExternalID = 'ExtID 10001';
        app2.MerchantID = 'Merchant 2000';

        app2.Product = 'ABP';
        app2.BusinessZip = '20716';
        app2.AgeOfBusinessYrs = '20130404';

        app2.HomeZip = '20716';
        app2.DateOfBirth = '20130404';

        app2.CloseDate = '20130504';

        app2.HomeState = 'MD';
        app2.ResidenceStatus = 'No';
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Opportunity New';
        opp.StageName = 'Approved';
        opp.CloseDate = System.today();
        opp.Current_Processor__c = 'ABC Global Systems';
        insert opp;
        
        Oppr_Document__c od3 = new Oppr_Document__c();
        od3.document_name__c = 'Four Months of Credit Statements (For MCA Products)';
        od3.Opportunity__c = opp.Id;
        od3.status__c = 'Requested';
        od3.RequiredDoc__c = true;
        insert od3;

        Oppr_Document__c od4 = new Oppr_Document__c();
        od4.document_name__c = 'Two Months of Bank Statements (For MCA Products)';
        od4.Opportunity__c = opp.Id;
        od4.status__c = 'Requested';
        od4.RequiredDoc__c = true;
        insert od4;

        Campaign cm = new Campaign();
        cm.Name = 'Biz2Credit';
        insert cm;

        SubmitApplication.ReturnSubmitAppDetails resp = SubmitApplication.doPost(app);
        SubmitApplication.ReturnSubmitAppDetails resp2 = SubmitApplication.doPost(app2);
        Test.stopTest();
    }
}