src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessStructure__c</fullName>
        <label>Business Structure</label>
        <picklist>
            <picklistValues>
                <fullName>C-Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Liability Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Liability Partnership</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <picklist>
            <picklistValues>
                <fullName>Large Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Supply Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bakery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar/Tavern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty/Nail/Spa Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bicycle Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candy Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carwash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell Phone Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiropractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer and Software Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consignment/Second Hand Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenience Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dentist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drug and Vitamin Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drycleaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics/TV and Radio Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Covering Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FederalTaxID__c</fullName>
        <label>Federal Tax ID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_or_State_Tax_Liens__c</fullName>
        <label>Federal or State Tax Liens?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flag_Account_for_Renewal__c</fullName>
        <formula>if( Most_Recent_Funded_Renewal_Date__c &lt; Most_Recent_Opp_Not_Processed__c ,0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flag Account for Renewal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Landlord_Agent_Name__c</fullName>
        <label>Landlord/Agent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Agent_Phone__c</fullName>
        <label>Landlord/Agent Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_For_Statements_etc__c</fullName>
        <description>Added per Earl and Karl.  This will be used for mailing purposed only and could be different for the actual retail location.</description>
        <label>Mailing Address (For Statements etc.)</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Present_Management_Since__c</fullName>
        <label>Present Management Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pricing_on_New_Deals__c</fullName>
        <label>Pricing on New Deals</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pricing_on_Renewals__c</fullName>
        <label>Pricing on Renewals</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Remaining_On_Lease__c</fullName>
        <label>Time Remaining On Site Lease/Mortgage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <formula>Account.Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Update in Account Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <formula>Account.Number_of_Locations__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <formula>Account.Number_of_Terminals_at_Location__c</formula>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <formula>Account.Owned_Business_Since__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updated From Account Owned Business Since Field.</inlineHelpText>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountMainBusiness.cls
global class AccountMainBusiness {
	global boolean isVisible { get; set; }
    global String btnText{get;set;}
    global Account objAccount{get;set;}
    global Opportunity opp{get;set;}

	global AccountMainBusiness() {

		try {
			btnText = 'Edit';
			isVisible = false;
			String oppid = ApexPages.currentPage().getParameters().get('id');
			if (oppid.trim() != '' && oppid != null) {
				opp = [SELECT accountid FROM Opportunity WHERE id = : oppid];
				if (opp.accountid != null) {
					objAccount = [SELECT 
									Legal_Name__c, Phone, Name, Fax, BillingState, Billingcity, Billingstreet, 
									Billingcountry, Email_Address__c, Mailing_Address_For_Statements_etc__c, 
									BillingPostalCode, Website, DateBusinessStarted__c, FederalTaxID__c, 
									BusinessType__c, Owned_Business_Since__c, Landlord_Agent_Name__c,
									Present_Management_Since__c, Landlord_Agent_Phone__c, Number_of_Locations__c,
									Time_Remaining_On_Lease__c, Number_of_Terminals_at_Location__c,
									Federal_or_State_Tax_Liens__c, Flag_Account_for_Renewal__c, 
									Pricing_on_New_Deals__c, Sic, Pricing_on_Renewals__c,
									BusinessStructure__c 
								  FROM 
								  	Account 
								  WHERE 
								  	id = : opp.accountid];
				} else {
					ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Opportunity does not have an Account ');
					ApexPages.addMessage(msg);

				}

			} else {
				ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Please Provide Opportunity Id');
				ApexPages.addMessage(msg);


			}
		} catch (Exception ex) {
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred' + ex.getMessage());
			ApexPages.addMessage(msg);
		}
	}
	global PageReference onEdit() {

		try {
            if (btnText == 'Edit') {
				isVisible = true;
				btnText = 'Save';
			} else {
                System.debug('=============== objAccount' +objAccount);
				if(objAccount != NULL || test.isRunningTest()){
					update objAccount;
					btnText = 'Edit';
					isVisible = false;
				}
			}

		} catch (Exception ex) {
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred');
			ApexPages.addMessage(msg);
		}

		return null;
	}
	global PageReference onCancel() {
		btnText = 'Edit';
		isVisible = false;
		return null;

	}
}