src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Sales_Check_List__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Check Lists</relationshipLabel>
        <relationshipName>Sales_Check_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Check List</label>
    <nameField>
        <label>Sales Check List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Check Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDealTerms_Ctrl.cls
@isTest
private class TestDealTerms_Ctrl {
    static testMethod void dealTerms_UnitTest() {
        CALC.ApexTesting();
        Test.startTest();
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm);
        Sales_Check_List__c slsclist = new Sales_Check_List__c();
        slsclist.Opportunity__c = opp.Id;
        insert slsclist;
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        DealTerms_Ctrl dealObj = new DealTerms_Ctrl();
        dealObj.doSave();
        Test.stopTest();
    }
}