src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <picklist>
            <picklistValues>
                <fullName>Large Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Supply Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bakery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar/Tavern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty/Nail/Spa Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bicycle Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candy Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carwash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell Phone Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiropractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer and Software Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consignment/Second Hand Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenience Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dentist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drug and Vitamin Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drycleaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics/TV and Radio Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Covering Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Principal_2_First_Name__c</fullName>
        <label>Principal 2 First Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_2_Last_Name__c</fullName>
        <label>Principal 2 Last Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchant__c.object
<CustomObject>
    <label>Merchant</label>
    <nameField>
        <displayFormat>Merchant-{0000}</displayFormat>
        <label>Merchant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Database_Entry_Due_Date__c</fullName>
        <label>Account Database Entry Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Database_Entry__c</fullName>
        <label>Account Database Entry</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <picklist>
            <picklistValues>
                <fullName>1st federal financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st First Source Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abanco INTERNATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC Global Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliant Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allied Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ameribank National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Credit Card Processing, Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAVINGS BANK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriMerchant Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMI-Merchant Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appstar Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic Stewardship Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVFUEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axia Corp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancard Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancfirst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BanCorpSouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankCard Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankcard USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banker&apos;s Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of America Merchant Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Entry_Date__c</fullName>
        <label>Data Entry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deal_Ready_For_Processing__c</fullName>
        <description>This deal has been checked by sales and is ready for BH data entry.</description>
        <label>Deal Ready For QC</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestFormulaFieldUtiity.cls
@isTest
public with sharing class TestFormulaFieldUtiity {

public static TestMethod void TestFormulaFieldUtility_Method(){
    CALC.ApexTesting();
    Account acc= new Account();
    acc.Name='test1';
    acc.BusinessType__c='Auto Service';
    Insert acc;
    
    Campaign camp=new Campaign();
    camp.Name= 'test1campaign';
    camp.Type='Internet';
    Insert camp;
    
    
    Opportunity opp=new Opportunity();
    opp.AccountId=acc.Id;
    opp.ForecastCategoryName='Pipeline';
    opp.Name='test1opportunity';
    opp.LeadSource='A001';
    opp.CampaignID=camp.Id;
    opp.CloseDate=System.Today();
    opp.StageName='Prospecting';
    opp.Current_Processor__c='Alpha Card';
   
    Insert opp;
    
   
    try{
    Merchant__c Merchnt = FormulaFieldUtility.objMerchant;
       }
        catch(Exception ex)   {   ApexPages.Message msg=new ApexPages.Message(ApexPages.Severity.Error,'An exception occurred');    ApexPages.addMessage(msg);  }
        
    Apexpages.currentpage().getparameters().put('oppId',opp.Id);
    /* ========================== Added Code ============== */
    
    String accountDatabaseEntryDaysCount = FormulaFieldUtility.accountDatabaseEntryDaysCount;
    String accountDatabaseEntryFlag = FormulaFieldUtility.accountDatabaseEntryFlag;
    String accRollupApproval = FormulaFieldUtility.accRollupApproval;
    
    /* ========= Added Code Ends here =========== */
    String TMWebDeclineReasons = FormulaFieldUtility.TMWebDeclineReasons;
    String totalDaysForDataEntry = FormulaFieldUtility.totalDaysForDataEntry;
    String totalDaysToDecision = FormulaFieldUtility.totalDaysToDecision;
    String totalDaysInQQAndUnderwriting = FormulaFieldUtility.totalDaysInQQAndUnderwriting;
    String totalDaysToRepay = FormulaFieldUtility.totalDaysToRepay;
    String typeOfBusiness = FormulaFieldUtility.typeOfBusiness;
    //String uCCBusinessStructure = FormulaFieldUtility.uCCBusinessStructure;
    //String mercIntDate = FormulaFieldUtility.merchantInterviewCompleted;
    Decimal applicant1PrevFICO = FormulaFieldUtility.applicant1PrevFICO;
    Decimal ccApplicant1PrevFICO = FormulaFieldUtility.ccApplicant1PrevFICO;
    Contact c  = FormulaFieldUtility.objContact;
    /*opp.Data_Entry_Date__c = Datetime.now();
    opp.Deal_Ready_For_Processing__c =  Datetime.now();
    opp.Decision_Date__c = Datetime.now();
    update opp;
    
    TMWebDeclineReasons = FormulaFieldUtility.TMWebDeclineReasons;
    totalDaysForDataEntry = FormulaFieldUtility.totalDaysForDataEntry;
    totalDaysToDecision = FormulaFieldUtility.totalDaysToDecision;
    totalDaysInQQAndUnderwriting = FormulaFieldUtility.totalDaysInQQAndUnderwriting;
    totalDaysToRepay = FormulaFieldUtility.totalDaysToRepay;
    typeOfBusiness = FormulaFieldUtility.typeOfBusiness;
    uCCBusinessStructure = FormulaFieldUtility.uCCBusinessStructure;
    mercIntDate = FormulaFieldUtility.merchantInterviewCompleted;
    applicant1PrevFICO = FormulaFieldUtility.applicant1PrevFICO;
    ccApplicant1PrevFICO = FormulaFieldUtility.ccApplicant1PrevFICO;*/
   
    FormulaFieldUtility ffu=new FormulaFieldUtility();
   
    FormulaFieldUtility.objMerchant=null;
    FormulaFieldUtility.opportunity = null;
    
    FormulaFieldUtility.objMerchant=null;
    FormulaFieldUtility.objContact=null;
    //FormulaFieldUtility.objUnderwriting=null;
    //FormulaFieldUtility.accountDatabaseEntryDaysCount=System.Today();
    //system.assert(System.Today(),opp.Account_Database_Entry_Due_Date__c);
}
 

    public static TestMethod void TestFormulaFieldUtility_Method2(){
        CALC.ApexTesting();
        
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm);
        Contact c = new Contact();
        c.Principal_2_First_Name__c = 'test1';
        c.Principal_2_Last_Name__c = 'test2';
        c.AccountId = acc.Id;
        c.LastName = 'test';
        insert c;
        Merchant__c Merchnt= TestUtils.createMerchant(opp);    
        
        Apexpages.currentpage().getparameters().put('oppId',opp.Id);    
        c  = FormulaFieldUtility.objContact;
        Merchnt = FormulaFieldUtility.objMerchant;
        
        String value1 = FormulaFieldUtility.approvalProcessTime;
        
        String value2 = FormulaFieldUtility.approvedFlag;
        String value3 = FormulaFieldUtility.approvedAmount;
        String value4 = FormulaFieldUtility.bakerFlag;
        String value5 = FormulaFieldUtility.beginActivityMonitoringDaysCount;
        String value6 = FormulaFieldUtility.beginActivityMonitoringFlag;
        String value7 = FormulaFieldUtility.businessInfo;
        String value8 = FormulaFieldUtility.businessOpenDate;
        String value9 = FormulaFieldUtility.businessPhone;
        String value10 = FormulaFieldUtility.calculatorVariance;
        String value11 = FormulaFieldUtility.campaignType;
        
    }
    
     public static TestMethod void TestFormulaFieldUtility_Method3(){
        CALC.ApexTesting();
        
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm);
        
        opp.Account_Database_Entry_Due_Date__c = Date.today();
        opp.Account_Database_Entry__c = Datetime.now();
        update opp;
        Apexpages.currentpage().getparameters().put('oppId',opp.Id);
        
        String value = FormulaFieldUtility.additionalSignerSSN;
        String value1 = FormulaFieldUtility.AE_PrimarySignerInfo;
     }
}