src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Time_Remaining_On_Lease__c</fullName>
        <label>Time Remaining On Site Lease/Mortgage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Additional_Locations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Locations</relationshipLabel>
        <relationshipName>Additional_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DBA_Name__c</fullName>
        <label>DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Phone__c</fullName>
        <label>Landlord Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <label>Landlord</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Remaining_on_Lease__c</fullName>
        <label>Time Remaining on Lease</label>
        <picklist>
            <picklistValues>
                <fullName>1-6 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7-11 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Years+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Additional Location</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Additional Locations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestExtjs_Applicant_Credit.cls
@isTest 
private class TestExtjs_Applicant_Credit {
    static testMethod void extjs_Applicant_Credit_UnitTest() {
    	CALC.apexTesting();
        Account acc = TestUtils.createAccount();
        Additional_Locations__c  aloc = TestUtils.createAdditionalLocation(acc);
        
        Extjs_Applicant_Credit.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Applicant_Credit.QueryObj queryObj = new Extjs_Applicant_Credit.QueryObj( );
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = acc.Id;
        queryObj.start = 0;
        queryObj.recordCount = 10;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> paramMap = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        queryObj.sortParams.add(paramMap );
        Extjs_Applicant_Credit.query(queryObj);
        
        Extjs_Applicant_Credit.CRUDData crudObj = new  Extjs_Applicant_Credit.CRUDData();
        crudObj.sobjname = 'Additional_Locations__c';
        crudObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj.oppId = acc.Id;
        crudObj.parentFieldName = 'Account__c';
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc );
        Map<String, String> fieldMap = new Map<String, String>{'Id' => aloc.Id, 'Street__c' => aloc.Street__c, 'Phone__c' => aloc.Phone__c,'State__c' => aloc.State__c, 'Time_Remaining_on_Lease__c' => aloc.Time_Remaining_on_Lease__c};
        crudObj.records = new List<Map<String, String>>{fieldMap};
        
        Extjs_Applicant_Credit.refreshObjects(crudObj, sobjList);
        Extjs_Applicant_Credit.create(crudObj);
        Extjs_Applicant_Credit.updat(crudObj);
        Extjs_Applicant_Credit.CRUDResponse crdrespose = Extjs_Applicant_Credit.delet(crudObj);
    }
}