src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>QC in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Offer Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documents Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer Rescinded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted For Funding Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Additional Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RequiredDoc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RequiredDoc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Oppr_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Oppr_Offers</relationshipLabel>
        <relationshipName>Oppr_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Offered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Oppr_Offer</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oppr_Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSendAcceptedOffers.cls
@isTest
public with sharing class TestSendAcceptedOffers {

    static testMethod void testDoPost() {
        
        Test.startTest();
        CALC.ApexTesting();
        Application app = new Application();
        String instanceUrl = Biz2CreditUtils.getInstanceURL();
        
        // Using unique identifier of source system for Acct and opportunity Name
        //Get List Of required fields - contact     
        app.FirstName = 'James';
        app.LastName = 'Jones';
        app.HomeCity = 'Washington';
        
        //Get List Of required fields - account
        app.BusinessCity = 'Washington DC';
        app.FederalTaxId = '111155555';
        
        //Get List Of required fields - opportunity
        app.AvgMonthSales = 50000;
        app.MajorCreditCardsProc = 'Visa';
        app.AvgMonthTrans = 45000;
        app.CCSalesLastMonth = 100000;
        app.CCSalesLast1Month = 45000;
        app.CCSalesLast2Month = 55000;
        app.CCSalesLast3Month = 65000;
        app.NumOfTransLastMonth = 300;
        app.NumOfTrans1Month = 250;
        app.NumOfTrans2Month = 350;
        app.NumOfTrans3Month = 450;
        app.SourceSystem = 'Biz2Credit';
        app.ExternalID = 'ExtID10001';
        app.MerchantID = 'Merchant 2000';
        
        Opportunity opp = Biz2CreditUtils.createOpportunity(app);  
        Oppr_Offer__c opprOffer = Biz2CreditUtils.createOpprOffer(opp.Id);
        
        Oppr_Document__c OppDoc = new Oppr_Document__c();
        OppDoc.Document_Name__c = 'testDoc';
        OppDoc.Additional_Notes__c = 'testDoc';
        OppDoc.Opportunity__c = opp.Id;
        OppDoc.Status__c = 'Requested';
        OppDoc.RequiredDoc__c = true;
        insert OppDoc;
        
        List<Oppr_Document__c> odcList = [SELECT id FROM Oppr_Document__c WHERE RequiredDoc__c = true AND status__c in ('Requested','Rejected') AND  Opportunity__c = : opp.id AND Id =: OppDoc.Id];
            
        OpportunityOffer oppOff = new OpportunityOffer();
        
        System.debug('opprOffer.Name....'+opprOffer.Name);
        // Correctly Entered data should give successful resp
        oppOff.OfferID = opprOffer.Name;
        oppOff.Amount = 1000;
        oppOff.DailyCollection = 1000;
        oppOff.Duration = 5;
        oppOff.ProductName = 'Product 1';
        oppOff.DailyPayment = 1000;
        oppOff.NumOfPayments = 6;
        oppOff.ExternalID = 'ExtID10001';
        oppOff.Source = 'B2C';
 
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.addHeader('Content-Type','application/x-www-form-urlencoded'); 
        req.requestURI = 'https://'+instanceUrl+'/services/apexrest/SendAcceptedOffers';  
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
         
        
        SendAcceptedOffers.ReturnSendOfferDetails resp1 = SendAcceptedOffers.doPost(oppOff);
        
        // Incorrectly ExternalID entered data should give error resp
        //oppOff.ExternalID = 'ExtID100';
        oppOff.ExternalID = 'ExtID10001';
        SendAcceptedOffers.ReturnSendOfferDetails resp2 = SendAcceptedOffers.doPost(oppOff);       
        
        // Incorrectly source entered data should give error resp
       // oppOff.Source = 'Biz2Cred';
       
        
        OpportunityOffer oppOff1 = new OpportunityOffer();
        // Correctly Entered data should give successful resp
        oppOff1.OfferID = opprOffer.Name;
        oppOff1.Amount = 1000;
        oppOff1.DailyCollection = 1000;
        oppOff1.Duration = 5;
        oppOff1.ProductName = 'Product 1';
        oppOff1.DailyPayment = 1000;
        oppOff1.NumOfPayments = 6;
        oppOff1.ExternalID = 'ExtID10001';
        oppOff1.Source = 'test';
        SendAcceptedOffers.ReturnSendOfferDetails resp3 = SendAcceptedOffers.doPost(oppOff1);
        
        opp.Status__c = 'Qualified Offer';
        update opp;
        
        SendAcceptedOffers.ReturnSendOfferDetails resp4 = SendAcceptedOffers.doPost(oppOff);
        Test.stopTest();
    }
}