src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <picklist>
            <picklistValues>
                <fullName>Large Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Supply Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bakery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar/Tavern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty/Nail/Spa Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bicycle Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camera Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candy Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carwash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell Phone Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiropractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer and Software Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consignment/Second Hand Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenience Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dentist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drug and Vitamin Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drycleaner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics/TV and Radio Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Covering Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FederalTaxID__c</fullName>
        <label>Federal Tax ID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Funding_Date__c</fullName>
        <label>First Funding Date</label>
        <summarizedField>Opportunity.Funded_by_WC__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Created_Opportunity__c</fullName>
        <label>Last Created Opportunity</label>
        <summarizedField>Opportunity.CreatedDate</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Renewal_Date__c</fullName>
        <label>Last Renewal Date</label>
        <summarizedField>Opportunity.CreatedDate</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.Renewal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Months_with_Current_Processor__c</fullName>
        <label>Months with Current Processor</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Funded_Renewal_Date__c</fullName>
        <label>Most Recent Funded Renewal Date</label>
        <summarizedField>Opportunity.Time_For_Renewal_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Roll_up_Approved__c</fullName>
        <label>Roll up Approved</label>
        <summaryFilterItems>
            <field>Opportunity.Renewal__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.Approved_Flag__c</field>
            <operation>equals</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Database_Entry_Due_Date__c</fullName>
        <label>Account Database Entry Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Database_Entry__c</fullName>
        <label>Account Database Entry</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Account_In_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account In Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Advance_ID__c</fullName>
        <externalId>true</externalId>
        <label>Advance ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Confirmed_business_DBA_name__c</fullName>
        <label>Confirmed business DBA name?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Funding_Date__c</fullName>
        <formula>Account.First_Funding_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Funding Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <formula>Account.Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Update in Account Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Term_Days__c</fullName>
        <label>Business Days to Collect (Loan)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months_with_Current_Processor__c</fullName>
        <formula>Account.Months_with_Current_Processor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Months with Current Processor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <formula>Account.Number_of_Locations__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <formula>Account.Number_of_Terminals_at_Location__c</formula>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <formula>Account.Owned_Business_Since__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updated From Account Owned Business Since Field.</inlineHelpText>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pay_Back_Amount__c</fullName>
        <label>Amount Sold</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Payback__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PrimaryCampaignSource__c</fullName>
        <formula>CASE(Campaign.Type ,
&quot;Internet&quot;, &quot;Internet&quot;,
&quot;Rapid Advance Internal Campaign&quot;, &quot;Rapid Advance Internal Campaign&quot;,
Campaign.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PrimaryCampaignSource</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>ACH Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Risk Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line of Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan w/MCA pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan w/ True-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preferred Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBA Bridge Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication ACH Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Loan w/MCA Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Loan w/ True-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Premium MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Starter Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Amount Sold (Previous Deal)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Renewal_Number__c</fullName>
        <label>Renewal Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Syndication_Amount__c</fullName>
        <label>Syndication Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Time_For_Renewal_Date__c</fullName>
        <formula>CloseDate + 150</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time For Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityDetail.cls
global class OpportunityDetail {

	public OpportunityDetail(ApexPages.StandardController controller) {
		
		try {
			isVisible = false;
			String op = ApexPages.currentPage().getParameters().get('id');
			
			if (op != null && op.trim() != '') {
				opp = [SELECT 
						   Renewal_Number__c, Renewal__c, campaign.name, Confirmed_business_DBA_name__c, 
						   Account_Database_Entry_Due_Date__c, Account_Database_Entry__c, Id, Name, StageName, Type, AccountId, 
						   Account.BillingCity, Account.BillingCountry, Account.BillingState,
						   Account.BillingStreet, Account.BillingPostalCode, Account.Roll_up_Approved__c, Account.Fax, 
						   Account.DateBusinessStarted__c, Account.Phone,
						   Account.Name, Account.FederalTaxID__c, Account.First_Funding_Date__c, 
						   Account.Most_Recent_Funded_Renewal_Date__c, Time_For_Renewal_Date__c, Account.Last_Renewal_Date__c,
						   CreatedDate, Account.Last_Created_Opportunity__c, Account.Legal_Name__c, 
						   Account.Months_with_Current_Processor__c,
						   Account.Number_of_Locations__c, Account.Number_of_Terminals_at_Location__c, Syndication_Amount__c, 
						   Product__c,
						   PrimaryCampaignSource__c, OwnerId, LastModifiedById, CreatedById, Amount, Advance_ID__c, 
						   Account_In_Risk__c,
						   Account.Owned_Business_Since__c, Account.BusinessType__c, Pay_Back_Amount__c, Percent_Payback__c, 
						   Loan_Term_Days__c,
						   Account.ownerId, Account.Type, Purchase_Amount__c, Underwriter_Assigned__c, 
						   Processing_Representative__c, Auto_Decisioned_By__c, Opportunity_Number__c, Processing_Rep_Assigned__c, 
						   Submit_to_UW_Processing__c, CALC_Link__c, Notes_Link__c 
					   FROM 
					       Opportunity 
					   WHERE 
					       Id = : op];
				
				EstimatedDailyTransactions = ((Decimal.valueof(FormulaFieldUtility.estimatedDailyRepay)).setScale(2)) + '';
			} 
			else {
				ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Please provide Opportunity ID');
				ApexPages.addMessage(msg);
			}
		} 
		catch (Exception ex) {
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred' + ex.getMessage());
			ApexPages.addMessage(msg);
		}
	}

	global boolean isVisible {get; set;}
    global String btntext {get; set;}
    global Opportunity opp {get; set;}
    global String EstimatedDailyTransactions {get; private set;}

	global OpportunityDetail() {
		
		btnText = 'Edit';
		try {
			isVisible = false;
			String op = ApexPages.currentPage().getParameters().get('id');
			
			if (op != null && op.trim() != '') {
				opp = [SELECT 
					   	Renewal_Number__c, Renewal__c, campaign.name, Confirmed_business_DBA_name__c, 
					   	Account_Database_Entry_Due_Date__c, Account_Database_Entry__c, Id, Name, StageName, Type, AccountId, 
					   	Account.BillingCity, Account.BillingCountry, Account.BillingState,
					   	Account.BillingStreet, Account.BillingPostalCode, Account.Roll_up_Approved__c, Account.Fax, 
					   	Account.DateBusinessStarted__c, Account.Phone,
					   	Account.Name, Account.FederalTaxID__c, Account.First_Funding_Date__c, 
					   	Account.Most_Recent_Funded_Renewal_Date__c, Time_For_Renewal_Date__c, Account.Last_Renewal_Date__c,
					   	CreatedDate, Account.Last_Created_Opportunity__c, Account.Legal_Name__c, 
					   	Account.Months_with_Current_Processor__c,
					   	Account.Number_of_Locations__c, Account.Number_of_Terminals_at_Location__c, Syndication_Amount__c, 
					   	Product__c,
					   	PrimaryCampaignSource__c, OwnerId, LastModifiedById, CreatedById, Amount, Advance_ID__c, 
					   	Account_In_Risk__c,
					   	Account.Owned_Business_Since__c, Account.BusinessType__c, Pay_Back_Amount__c, Percent_Payback__c, 
					   	Loan_Term_Days__c,
					   	Account.ownerId, Account.Type, Purchase_Amount__c, Underwriter_Assigned__c, 
					   	Processing_Representative__c, Auto_Decisioned_By__c, Opportunity_Number__c, Processing_Rep_Assigned__c, 
					   	Submit_to_UW_Processing__c, CALC_Link__c, Notes_Link__c 
					   FROM 
					   	Opportunity 
					   WHERE 
					   	Id = : op];
					   
				EstimatedDailyTransactions = ((Decimal.valueof(FormulaFieldUtility.estimatedDailyRepay)).setScale(2)) + '';
			} 
			else {
				ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Please provide Opportunity ID');
				ApexPages.addMessage(msg);
			}
		} 
		catch (Exception ex) {
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred' + ex.getMessage());
			ApexPages.addMessage(msg);
		}
	}
	
	global PageReference onEdit11() {
		isVisible = true;
		return null;
	}

	global PageReference onEdit() {

		try {
			//if(btntext=='Edit'){
			//    isVisible = true;
			//   btntext='Save';
			//    }
			//    else{
			if(opp != null){
				update opp;
				update opp.Account;
				update opp.Campaign;
			//    btntext='Edit';
			//    isVisible = false;
			// }
			}
		} 
		catch (Exception ex) {
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred');
			ApexPages.addMessage(msg);
		}

		return null;
	}
	
	global PageReference onCancel() {
		
		btntext = 'Edit';
		isVisible = false;
		return null;
	}
}