src/objects/CampaignByLeadType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used in Trigger to map values</description>
    <fields>
        <fullName>CampaignID__c</fullName>
        <label>CampaignID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CampaignByLeadType</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>RC_Lead_Type__c</fullName>
        <label>RC Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>RAFRESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAPQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAFC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RADM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAQS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RABC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RATV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAPPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RALEND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RADM2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RCRAAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAFREXP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAFRESHQS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAFRESHAGED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RACK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RALT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCreateCampaignMemberForRockConn.cls
@istest

public class TestCreateCampaignMemberForRockConn
{

    public static testmethod void runTestForRockConn()
    {
        
        PartnerNetworkConnection pnc = new PartnerNetworkConnection();
        pnc.connectionname = 'Rock Connections';
        pnc.ConnectionStatus = 'Accepted';
        //insert pnc;
        
        List<PartnerNetworkConnection> pncList=[select id,connectionname from PartnerNetworkConnection where id =: pnc.id];
        
        Lead lTemp=new Lead();
        CALC.ApexTesting();

        lTemp.Status='Calling - No Contact Made';
        lTemp.LeadSource='Radio';
        lTemp.Company='test company';
        lTemp.Phone='415789415';
        lTemp.Lastname='lastname'; 
        lTemp.RC_Lead_Type__c='RAFF';               
        insert lTemp;
   
        List<PartnerNetworkRecordConnection> lstShareRecords= new List<PartnerNetworkRecordConnection>();
        
        for(PartnerNetworkConnection network : pncList) {
        
        PartnerNetworkRecordConnection newrecord = new PartnerNetworkRecordConnection();
        
        newrecord.ConnectionId = network.Id;
        newrecord.LocalRecordId = lTemp.id;
       // newrecord.RelatedRecords = 'Lead';
        newrecord.SendClosedTasks = false;
        newrecord.SendOpenTasks = false;
        newrecord.SendEmails = false;
        
        lstShareRecords.add(newrecord);
        }
        //if (test.IsRunningTest()==false)
        //insert lstshareRecords;
        
        Campaign camp = new Campaign();
        camp.Name = 'testCamp';
        camp.Type= 'Lead Source';
        insert camp;
        
        CampaignByLeadType__c campType = new CampaignByLeadType__c();
        campType.Name = 'test CampaignByLeadType';
        campType.CampaignID__c = camp.Id;
     }
            

}