src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Sales_Team_Member_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Fund_Set_Up__c</fullName>
        <label>Split Fund Set Up</label>
        <picklist>
            <picklistValues>
                <fullName>Rapid Advance Chooses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPS - Rocky Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Calculate_Due_Dates__c</fullName>
        <label>Calculate Due Dates</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <picklist>
            <picklistValues>
                <fullName>1st federal financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st First Source Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abanco INTERNATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC Global Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliant Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allied Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ameribank National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Credit Card Processing, Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAVINGS BANK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriMerchant Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMI-Merchant Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appstar Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic Stewardship Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVFUEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axia Corp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancard Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancfirst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BanCorpSouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankCard Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Card Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankcard USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banker&apos;s Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of America Merchant Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Manager_s_Override__c</fullName>
        <label>Manager&apos;s Override</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notified_NxGen_of_Approval__c</fullName>
        <label>Notified NxGen of Approval</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Opportunity record is a clone from a previous opportunity, the link to that original opportunity will be here.  No one has to fill this in manually.</inlineHelpText>
        <label>Previous Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor_Name__c</fullName>
        <inlineHelpText>If updated, update also current processor field</inlineHelpText>
        <label>New Processor</label>
        <picklist>
            <picklistValues>
                <fullName>Alpha Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancard Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benchmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Card Payment Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Century Bankcard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chosen Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cynergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Fixed-Amount ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Payments Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Processing Services, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elite Data-ChasePaymentech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EVO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evolution Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First American Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Data – Omaha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ForwardLine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humboldt Merchant Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRN Payment Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lockbox-KBT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mercury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moneris/Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nationwide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Re_Decision_Date__c</fullName>
        <description>Decision for this deal has been changed.</description>
        <label>Re-Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Split_Fund_Set_Up__c</fullName>
        <label>Split Fund Set Up</label>
        <picklist>
            <picklistValues>
                <fullName>GPS - Rocky Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rapid Advance Chooses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submit_to_Sales_Assistant__c</fullName>
        <label>Submit to Sales Assistant</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Underwriting_Approval__c</fullName>
        <label>Underwriting Decision</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by Credit Committee with conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined by Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined - Pending Management Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Management Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending management review returned to u/w</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Comp. Pay Off too High - Reconsider Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Will Not Reconsider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Will Reconsider in the Future</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestTrigger.cls
/*

Modified
DS-CONAM - 03/04/2015
Version 10 to 32
Added @istest Annotation
Added Test.startTest() and Test.stopTest() to both methods
*/


@istest
public class TestTrigger {
    
    static testMethod void myTest() {

        Test.startTest();
        testOppDates();
        testRenewalClone();
        Test.stopTest();
    }

    static void testRenewalClone() {

        CALC.ApexTesting();
        User u = [SELECT id FROM User WHERE isActive = true limit 1];
        
        Opportunity o = new Opportunity(Name = 'Test Opportunity 12345', 
                                        CloseDate = System.today(), 
                                        StageName = 'Closed Deal', 
                                        Calculate_Due_Dates__c = System.now(), 
                                        Manager_s_Override__c = 0);
        insert o;

        OpportunityTeamMember newotm = new OpportunityTeamMember();
        newotm.OpportunityId = o.id;
        newotm.UserId = u.id;
        newotm.TeamMemberRole = 'Partner Sales Representative';
        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
        insert newotm;

        Opportunity o2 = new Opportunity(Name = 'Test Opportunity 12345', 
                                         CloseDate = System.today(), 
                                         StageName = 'Closed Deal', 
                                         Calculate_Due_Dates__c = System.now(), 
                                         Manager_s_Override__c = 0);
        o2.previous_opportunity__c = o.id;
        insert o2;

    }
    
    static void testOppDates() {
        
        CALC.ApexTesting();
        User u = [SELECT id FROM User WHERE isActive = true limit 1];
        
        Campaign c = new Campaign();
        c.Name = 'test';
        c.Sales_Team_Member_1__c = u.id;
        c.Sales_Team_Member_2__c = u.id;
        c.Sales_Team_Member_3__c = u.id;
        c.Sales_Team_Member_4__c = u.id;
        c.Sales_Team_Member_5__c = u.id;
        c.Sales_Team_Member_6__c = u.id;
        insert c;

        Opportunity o = new Opportunity(Name = 'Test Opportunity 12345', 
                                        Closedate = System.today(), 
                                        StageName = 'Closed Deal', 
                                        Calculate_Due_Dates__c = System.now(), 
                                        Manager_s_Override__c = 0);
                                        
        o.CampaignId = c.id;
        o.Decision_Date__c = System.now();
        o.Submit_To_Sales_Assistant__c = System.now();
        o.Re_Decision_Date__c = System.now();
        o.Notified_NxGen_of_Approval__c = System.now();
        insert o;

        ApexServices.CountBusinessDays(System.now(), System.now());

        o.Split_Fund_Set_Up__c = 'GPS - Rocky Mountain';
        update o;

        o.Split_Fund_Set_Up__c = 'Rapid Advance Chooses';
        update o;

        o.Split_Fund_Set_Up__c = 'xxx';
        o.Current_Processor__c = 'Nova';
        o.Processor_Name__c = 'Nova';
        update o;

        o.Current_Processor__c = 'Nova';
        o.Processor_Name__c = 'xxy';
        update o;

        o.Renewal__c = true;
        update o;

        o.Underwriting_Approval__c = 'Declined';
        update o;

        o.Underwriting_Approval__c = 'Auto Declined';
        update o;

        O.QC_Issue_Return_to_Sales_Assistant__c = 'TEST qc';
        update o;

        o.Processing_Re_Set__c = system.now();
        update o;
    }
}