src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Sales_Team_Member_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns6</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>All_Approved_With_Conditions_Met__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Approved With Conditions Met:</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Decisioned_By__c</fullName>
        <label>Auto Decisioned By</label>
        <picklist>
            <picklistValues>
                <fullName>AH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>If_Renewal_Preceding_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>If Renewal, Preceding Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Renewal_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Advance_Price__c</fullName>
        <label>New Advance Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_FRSA_Has_Been_Received__c</fullName>
        <description>Deal was reprised and we have received the new FRSA</description>
        <label>New FRSA Has Been Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Payback_Price__c</fullName>
        <label>New Amount Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Percent_Payback__c</fullName>
        <label>New Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <description>Opportunity ID Number</description>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Pay_Back_Amount__c</fullName>
        <label>Amount Sold</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Paid_Off__c</fullName>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_Payback__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Processing_Error_Date__c</fullName>
        <label>Processing Error Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Representative__c</fullName>
        <description>What RapidAdvance Processing Rep has this account?</description>
        <label>Processing Representative</label>
        <picklist>
            <picklistValues>
                <fullName>Amanda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atiya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cassandra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Katara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tina</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Amount Sold (Previous Deal)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Risk_Employee__c</fullName>
        <label>Risk Employee</label>
        <picklist>
            <picklistValues>
                <fullName>Deborah Oliver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gil Bowen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marlowe Rogers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tony Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vanessa Waller</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send_Risk_Alert_From__c</fullName>
        <description>Email corresponding with the named Risk Employee</description>
        <label>Send Risk Alert From</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Send_Risk_Alert_To__c</fullName>
        <description>Recipient of the Alert email</description>
        <label>Send Risk Alert To</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Send_Risk_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fires off a workflow to send an Email notification</description>
        <label>Send Risk Alert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Repay_Amount__c</fullName>
        <label>Total Transactions Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UWEligible_for_Rapid_Funding__c</fullName>
        <label>Eligible for Rapid Funding?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Once Funding Condition is met</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UW_Assigned_Date_Stamp__c</fullName>
        <label>UW Assigned Date Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assigned__c</fullName>
        <label>Underwriter Assigned:</label>
        <picklist>
            <picklistValues>
                <fullName>AUTO DECISION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CREDIT COMMITTEE OVERIDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aisha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dylan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ericka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greg Dye</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>John</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pamela</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theresa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vashia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cassandra</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User_Lookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Quick reference list of emails associated with particular strings, for conversion from Picklist values.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>User Lookup</label>
</CustomObject>

src/classes/OpportunityTriggerhandlerCls.cls
public with sharing class OpportunityTriggerhandlerCls {

    public static Boolean runOnce = false;

    public static void onAfterInsert(List<Opportunity> oppList) {
        runOnce = true;
        boolean checkRenewal = false;
        String parentOppId;
        List<OpportunityContactRole> oppRoleInsertList = new List<OpportunityContactRole> ();
        OpportunityContactRole oppContactRoleObj;
        String currentID;

        for (Opportunity opps: oppList) {
            if (opps.If_Renewal_Preceding_Opportunity__c != null) {
                currentID = opps.Id;
                checkRenewal = true;
                parentOppId = opps.If_Renewal_Preceding_Opportunity__c;
                System.debug('checkRenewal......' + checkRenewal + '.....parentOppId....' + parentOppId);
            }
        }
        if (checkRenewal) {
            List<OpportunityContactRole> oppRoleList = [SELECT Id, Role, OpportunityId, IsPrimary, ContactId FROM
            OpportunityContactRole WHERE
            OpportunityId = : parentOppId and
            Contact.IsDeleted = false];
            if (oppRoleList != null && oppRoleList.size()> 0) {
                for (OpportunityContactRole opprole: oppRoleList) {
                    oppContactRoleObj = new OpportunityContactRole();
                    oppContactRoleObj.OpportunityId = currentID;
                    oppContactRoleObj.ContactId = opprole.ContactId;
                    oppContactRoleObj.Role = opprole.Role;

                    if (opprole.IsPrimary == true) {
                        oppContactRoleObj.IsPrimary = true;
                    }
                    oppRoleInsertList.add(oppContactRoleObj);
                }
                if (oppRoleInsertList.size()> 0) {
                    try {
                        insert oppRoleInsertList;
                    } catch (Exception ex) {
                        System.debug('exception in insert role....' + ex.getMessage());
                    }
                }
            }
        }
    }

    public static void UnderwritingOpprtunityUpdate(List<Opportunity> oppoList, Map<Id, Opportunity> oldOppValues) {

        Opportunity oldOpp;
        List<Messaging.SingleEmailMessage> mailingList = new List<Messaging.SingleEmailMessage> ();

        for (Opportunity opp: oppoList) {

            oldOpp = oldOppValues.get(opp.Id);

            if (((oldOppValues.get(opp.Id).Auto_Decisioned_By__c == null) && (opp.Auto_Decisioned_By__c != null) && (opp.Underwriter_Assigned__c == 'AUTO DECISION')) || (oldOppValues.get(opp.Id).Underwriter_Assigned__c == null && opp.Underwriter_Assigned__c != null)) {

                opp.UW_Assigned_Date_Stamp__c = Datetime.now();
            }
            if (opp.UWEligible_for_Rapid_Funding__c == 'Yes' && (Trigger.isInsert || (Trigger.isUpdate && oldOpp.UWEligible_for_Rapid_Funding__c != 'Yes'))) {
                List<User> userListRoles = new List<User> ();
                userListRoles = [SELECT Id, Email FROM User WHERE UserRoleId IN(Select Id from UserRole where Name = 'Processors') and IsActive = true];
                List<User> userListsingle = [SELECT Id, Email FROM User WHERE IsActive = true and Username = 'mcerminaro@rapidadvance.com'
                Limit 1];
                if (userListsingle != null && !userListsingle.isEmpty()) {
                    userListRoles.add(userListsingle.get(0));
                }
                String[] toaddress = new String[] {};
                for (User user: userListRoles) {
                    if (user.Email != null && !user.Email.trim().equals('')) {
                        if (opp.Id == '0067000000VHvZw') {
                            toaddress.add('dshapiro@rainmaker-llc.com');
                            toaddress.add('adubedi@rainmaker-llc.com');
                            toaddress.add('achauhan@rainmaker-llc.com');
                        } else {
                            toaddress.add(user.Email);
                        }


                    }
                }

                System.debug('userListRoles...' + userListRoles.size());
                if (userListRoles != null && !userListRoles.isEmpty()) {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    //  mail.setToAddresses(toaddress); 
                    mail.setToAddresses(toaddress);
                    //mail.setReplyTo('services@rapidadvance.com');
                    //mail.setSenderDisplayName('Rapid Financial Services');
                    mail.setBccSender(false);
                    mail.setSubject(opp.Name + ' is Eligible for Rapid Funding');
                    mail.setPlainTextBody(opp.Name + ' is Eligible for Rapid Funding' + '\nOppId: ' + opp.Opportunity_Number__c);
                    mailingList.add(mail);
                }
            }

            /*** Alexandra Approval With Conditions WFR AND Umaru All Approved Conditions WFR ***/
            if ((opp.Processing_Representative__c == 'Alexandra' || opp.Processing_Representative__c == 'Umaru') && opp.All_Approved_With_Conditions_Met__c && (Trigger.isInsert || (Trigger.isUpdate && !((oldOpp.Processing_Representative__c == 'Alexandra' || oldOpp.Processing_Representative__c == 'Umaru') && oldOpp.All_Approved_With_Conditions_Met__c)))) {
                List<User> userList;
                if (opp.Processing_Representative__c == 'Alexandra') {
                    userList = [SELECT Id, Email FROM User WHERE IsActive = true and userName = 'apompee@rapidadvance.com'];
                } else if (opp.Processing_Representative__c == 'Umaru') {
                    userList = [SELECT Id, Email FROM User WHERE IsActive = true and userName = 'umansarnay@rapidadvance.com'];
                }

                if (userList != null && !userList.isEmpty()) {
                    String emailSubject = opp.Name + ' - ' + opp.Opportunity_Number__c + ' All approval conditions have been satisfied.';
                    String emailBody = '';
                    String[] toaddress = new String[] {};
                    if (userList.get(0) != null && userList.get(0).Email != null && !userList.get(0).Email.trim().equals('')) {

                        if (opp.Id == '0067000000VHvZw') {
                            toaddress.add('dshapiro@rainmaker-llc.com');
                            toaddress.add('adubedi@rainmaker-llc.com');
                            toaddress.add('achauhan@rainmaker-llc.com');
                        } else {
                            toaddress.add(userList.get(0).Email);
                        }
                    }
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(toaddress);
                    mail.setsubject(emailSubject);
                    mail.setBccSender(false);
                    mail.setPlainTextBody(emailBody);
                    mailingList.add(mail);
                }
            }

        }


        try {
            if (!mailingList.isEmpty()) {
                Messaging.sendEmail(mailingList);
            }
        } catch (Exception e) {
            System.debug('Error ::' + e.getMessage());
        }

    }

    public static void UnderwritingOpprtunityInsert(List<Opportunity> opList) {

        List<Messaging.SingleEmailMessage> mailingList = new List<Messaging.SingleEmailMessage> ();


        for (Opportunity opp: opList) {

            if ((opp.Auto_Decisioned_By__c != null && opp.Underwriter_Assigned__c == 'AUTO DECISION') || (opp.Underwriter_Assigned__c != null)) {

                opp.UW_Assigned_Date_Stamp__c = Datetime.now();

            }

            if (opp.UWEligible_for_Rapid_Funding__c == 'Yes') {
                List<User> userListRoles = new List<User> ();
                userListRoles = [SELECT Id, Email FROM User WHERE UserRoleId IN(Select Id from UserRole where Name = 'Processors') and IsActive = true];
                List<User> userListsingle = [SELECT Id, Email FROM User WHERE IsActive = true and Username = 'mcerminaro@rapidadvance.com'
                Limit 1];
                if (userListsingle != null && !userListsingle.isEmpty()) {
                    userListRoles.add(userListsingle.get(0));
                }
                String[] toaddress = new String[] {};
                for (User user: userListRoles) {
                    if (user.Email != null && !user.Email.trim().equals('')) {
                        if (opp.Id == '0067000000VHvZw') {
                            toaddress.add('dshapiro@rainmaker-llc.com');
                            toaddress.add('adubedi@rainmaker-llc.com');
                            toaddress.add('achauhan@rainmaker-llc.com');
                        } else {
                            toaddress.add(user.Email);
                        }


                    }
                }

                System.debug('userListRoles...' + userListRoles.size());
                if (userListRoles != null && !userListRoles.isEmpty()) {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    //  mail.setToAddresses(toaddress); 
                    mail.setToAddresses(toaddress);
                    //mail.setReplyTo('services@rapidadvance.com');
                    //mail.setSenderDisplayName('Rapid Financial Services');
                    mail.setBccSender(false);
                    mail.setSubject(opp.Name + ' is Eligible for Rapid Funding');
                    mail.setPlainTextBody(opp.Name + ' is Eligible for Rapid Funding' + '\nOppId: ' + opp.Opportunity_Number__c);
                    mailingList.add(mail);
                }
            }

            /*** Alexandra Approval With Conditions WFR AND Umaru All Approved Conditions WFR ***/
            if ((opp.Processing_Representative__c == 'Alexandra' || opp.Processing_Representative__c == 'Umaru') && opp.All_Approved_With_Conditions_Met__c) {
                List<User> userList;
                if (opp.Processing_Representative__c == 'Alexandra') {
                    userList = [SELECT Id, Email FROM User WHERE IsActive = true and userName = 'apompee@rapidadvance.com'];
                } else if (opp.Processing_Representative__c == 'Umaru') {
                    userList = [SELECT Id, Email FROM User WHERE IsActive = true and userName = 'umansarnay@rapidadvance.com'];
                }

                if (userList != null && !userList.isEmpty()) {
                    String emailSubject = opp.Name + ' - ' + opp.Opportunity_Number__c + ' All approval conditions have been satisfied.';
                    String emailBody = '';
                    String[] toaddress = new String[] {};
                    if (userList.get(0) != null && userList.get(0).Email != null && !userList.get(0).Email.trim().equals('')) {

                        if (opp.Id == '0067000000VHvZw') {
                            toaddress.add('dshapiro@rainmaker-llc.com');
                            toaddress.add('adubedi@rainmaker-llc.com');
                            toaddress.add('achauhan@rainmaker-llc.com');
                        } else {
                            toaddress.add(userList.get(0).Email);
                        }
                    }
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(toaddress);
                    mail.setsubject(emailSubject);
                    mail.setBccSender(false);
                    mail.setPlainTextBody(emailBody);
                    mailingList.add(mail);
                }
            }

        }


        try {
            if (!mailingList.isEmpty()) {
                Messaging.sendEmail(mailingList);
            }
        } catch (Exception e) {
            System.debug('Error ::' + e.getMessage());
        }
    }

    public static void RiskAlertUpdate(List<Opportunity> oppoList, Map<Id, Opportunity> oldOppValues) {

        for (Opportunity opp: oppoList) {
            if (opp.Processing_Error_Date__c != NULL && opp.Processing_Error_Date__c != oldOppValues.get(opp.Id).Processing_Error_Date__c) {

                User_Lookup__c toVal = User_Lookup__c.getValues(opp.Processing_Representative__c);
                User_Lookup__c fromVal = User_Lookup__c.getValues(opp.Risk_Employee__c);

                if (toVal != NULL) {
                    opp.Send_Risk_Alert_To__c = toVal.Email__c;
                }
                if (fromVal != NULL) {
                    opp.Send_Risk_Alert_From__c = fromVal.Email__c;
                }
                if (opp.Send_Risk_Alert_To__c != NULL && opp.Send_Risk_Alert_From__c != NULL) {
                    opp.Send_Risk_Alert__c = true;
                }
            } // end if
        }
    }

    public static void CalcualtePercentPaidOffTriggerInsert(List<Opportunity> oppoList) {
        for(Opportunity opp: oppoList){
        
         
         if(opp.Total_Repay_Amount__c != null && opp.Purchase_Amount__c != null && opp.Purchase_Amount__c > 0) {
            opp.Percent_Paid_Off__c = (opp.Total_Repay_Amount__c/ opp.Purchase_Amount__c);
         }
         
         /*** Percent Payback FU WFR ***/
         if(opp.New_FRSA_Has_Been_Received__c !=Null ) {
            opp.Percent_Payback__c= opp.New_Percent_Payback__c;
         }
        
         /*** Payback Amount FU WFR ***/
         if(opp.New_FRSA_Has_Been_Received__c != Null ){
            opp.Pay_Back_Amount__c = opp.New_Payback_Price__c;
         }
        
         /*** Reprice Amount FU **/ 
         if(opp.New_FRSA_Has_Been_Received__c !=Null ){
            opp.Amount = opp.New_Advance_Price__c;
         }
     }
    }

    public static void CalcualtePercentPaidOffTriggerUpdate(List<Opportunity> newoppoList, Map<Id, Opportunity> oldOppValues) {

        Opportunity oldOpp;
        for (Opportunity opp: newoppoList) {


            oldOpp = oldOppValues.get(opp.Id);

            if (opp.Total_Repay_Amount__c != null && opp.Purchase_Amount__c != null && opp.Purchase_Amount__c> 0) {
                opp.Percent_Paid_Off__c = (opp.Total_Repay_Amount__c / opp.Purchase_Amount__c);
            }

            /*** Percent Payback FU WFR ***/
            if (opp.New_FRSA_Has_Been_Received__c != Null && oldOpp.New_FRSA_Has_Been_Received__c == Null) {
                opp.Percent_Payback__c = opp.New_Percent_Payback__c;
            }

            /*** Payback Amount FU WFR ***/
            if (opp.New_FRSA_Has_Been_Received__c != Null && oldOpp.New_FRSA_Has_Been_Received__c == Null) {
                opp.Pay_Back_Amount__c = opp.New_Payback_Price__c;
            }

            /*** Reprice Amount FU **/
            if (opp.New_FRSA_Has_Been_Received__c != Null && oldOpp.New_FRSA_Has_Been_Received__c == Null) {
                opp.Amount = opp.New_Advance_Price__c;
            }
        }
    }
    
     public static void opportunityCampaignChosenInsert(List<Opportunity> oppoList) {
     
        List<id> campaignids = new List<id>();
        
        for (integer i = 0; i<oppoList.Size(); i++ ) {
            if (oppoList[i].CampaignId != null) {
            
                campaignids.add(oppoList[i].CampaignId);         
            } 
        }   

        Map<id, campaign> campaigns = new Map<id, campaign>([select id, name, Sales_Team_Member_1__c,Sales_Team_Member_2__c,Sales_Team_Member_3__c,Sales_Team_Member_4__c,Sales_Team_Member_5__c,Sales_Team_Member_6__c from campaign where id in :campaignids]);
        List<opportunityteammember> newlist = new List<opportunityteammember>();
        
        for (integer i = 0; i<oppoList.Size(); i++ ) {
            if (oppoList[i].CampaignId != null) {
                opportunity o = oppoList[i];
        
                campaign c = campaigns.get(o.campaignid);
                if (c != null) {
                    if (c.Sales_Team_Member_1__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_1__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   

                    if (c.Sales_Team_Member_2__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_2__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_3__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_3__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_4__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_4__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_5__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_5__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_6__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_6__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                }
            } 
        }   
        if (newlist.size()> 0) {
            insert newlist; 
        }
     }
     
     public static void opportunityCampaignChosenUpdate(List<Opportunity> oppoList, List<Opportunity> oldOppValues) {
     
         List<id> campaignids = new List<id>();
        
        for (integer i = 0; i<oppoList.Size(); i++ ) {
            if (oppoList[i].CampaignId != null && 
                    (Trigger.isUpdate && oppoList[i].CampaignId != oldOppValues[i].CampaignId )) {
            
                campaignids.add(oppoList[i].CampaignId);         
            } 
        }   

        Map<id, campaign> campaigns = new Map<id, campaign>([select id, name, Sales_Team_Member_1__c,Sales_Team_Member_2__c,Sales_Team_Member_3__c,Sales_Team_Member_4__c,Sales_Team_Member_5__c,Sales_Team_Member_6__c from campaign where id in :campaignids]);
        List<opportunityteammember> newlist = new List<opportunityteammember>();
        
        for (integer i = 0; i < oppoList.Size(); i++ ) {
            if (oppoList[i].CampaignId != null && 
                    (Trigger.isUpdate && oppoList[i].CampaignId != oldOppValues[i].CampaignId )) {
                opportunity o = oppoList[i];
        
                campaign c = campaigns.get(o.campaignid);
                if (c != null) {
                    if (c.Sales_Team_Member_1__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_1__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   

                    if (c.Sales_Team_Member_2__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_2__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_3__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_3__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_4__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_4__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_5__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_5__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                    if (c.Sales_Team_Member_6__c != null ) {
                        opportunityteammember newotm = new opportunityteammember();
                        newotm.OpportunityId = o.id;
                        newotm.UserId = c.Sales_Team_Member_6__c;
                        newotm.TeamMemberRole = 'Partner Sales Representative';
                        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
                        newlist.add(newotm);
                    }   
                }
            } 
        }   
        if (newlist.size()> 0) {
            insert newlist; 
        }
        }
    
}