src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Default_Opportunity_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CampaignsAssociated</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Percent_Paid_Off__c</fullName>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>ACH Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Risk Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line of Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan w/MCA pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan w/ True-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preferred Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBA Bridge Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication ACH Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Loan w/MCA Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Loan w/ True-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Premium MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Starter Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State_Of_Location__c</fullName>
        <label>State Of Location</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submit_to_UW_Processing__c</fullName>
        <label>Submit to UW &amp; Processing</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestUpdateOpportunityOwner.cls
@isTest
private class TestUpdateOpportunityOwner {

	static testMethod void myUnitTest() {
		
		Test.startTest();
		CALC.ApexTesting();
		User u = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND isActive = true Limit 1];
		Campaign cTest = new Campaign(Name = 'Test Campagin', Type = 'Internet', Default_opportunity_owner__c = u.id);
		insert cTest;

		Profile p = [SELECT Id FROM Profile WHERE Name = 'system administrator'];
		User uNew = new User(Alias = 'standt', Email = 'standarduser@ra.com',
							 	EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
								LocaleSidKey = 'en_US', ProfileId = p.Id,
								TimeZoneSidKey = 'America/Los_Angeles', UserName = 'standarduser@ra.com');

		System.runAs(uNew) {

			Opportunity opp = new Opportunity();
			opp.Name = 'testopp';
			opp.StageName = 'Open';
			opp.CloseDate = Date.today();
			opp.Submit_to_UW_Processing__c = System.now();
			opp.Product__c = 'Loan';
			opp.Percent_Paid_Off__c = 55;
			opp.State_Of_Location__c = 'CT';
			opp.CampaignId = ctest.id;
			insert opp;
		}
	}
}