src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Additional_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Owner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>User Type must be Standard SalesForce.</errorMessage>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BD_Send_Addtl_Owner__c</fullName>
        <label>Send Notifications Additional Owner</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>BD_Send_Cmpn_Owner__c</fullName>
        <label>Send Notifications Campaign Owner</label>
        <type>Email</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/classes/Test_CampaignOwnerChange.cls
@isTest (SeeAllData=true)
public class Test_CampaignOwnerChange {

   static testMethod void OwnerChange() {
      // Get a few admins to work with
      User[] admins = [SELECT Id,Email FROM User WHERE ProfileId = '00e30000000h0Bs' AND IsActive=true
                       AND Email!= NULL LIMIT 5];

      Campaign c = new Campaign();
      c.Name = 'Test Campaign';
      System.debug('+++ ' + admins[0].Id);
      c.OwnerId = admins[0].Id;
      Database.SaveResult sr = Database.insert(c);
      Id checkId = sr.GetID();
      Campaign[] campaignCheck = [SELECT Id,BD_Send_Cmpn_Owner__c FROM Campaign WHERE Id=: checkId];
      System.assertEquals(admins[0].Email,campaignCheck[0].BD_Send_Cmpn_Owner__c);
      
      // Test Additional Owner Assignment
      c.Additional_Owner__c = admins[1].Id;
      update c;
      campaignCheck = [SELECT Id,BD_Send_Addtl_Owner__c FROM Campaign WHERE Id=: checkId];
      System.assertEquals(admins[1].Email,campaignCheck[0].BD_Send_Addtl_Owner__c);
   }

} // end class