src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Re_Decision_Date__c</fullName>
        <description>Decision for this deal has been changed.</description>
        <label>Re-Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UCC_Date__c</fullName>
        <label>UCC Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UCC_Filing_Reason__c</fullName>
        <label>UCC Filing Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Addendum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCC_Filing__c</fullName>
        <label>UCC Filing</label>
        <picklist>
            <picklistValues>
                <fullName>Full UCC-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification UCC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCC_Filings__c</fullName>
        <label>UCC Filings:</label>
        <picklist>
            <picklistValues>
                <fullName>Full UCC-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification UCC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCC_Request_Date__c</fullName>
        <label>UCC Request Date:</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Underwriting_Approval__c</fullName>
        <label>Underwriting Decision</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by Credit Committee with conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined by Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined - Pending Management Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Management Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending management review returned to u/w</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Comp. Pay Off too High - Reconsider Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Will Not Reconsider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Will Reconsider in the Future</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Underwriting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriting</label>
        <referenceTo>Underwriting__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Underwriting__c.object
<CustomObject>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <label>Decision Date:</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Underwriting</relationshipLabel>
        <relationshipName>Underwriting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RE_Decision_Date__c</fullName>
        <label>RE-Decision Date:</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UCC_Filing_Reason__c</fullName>
        <label>UCC Filing Reason:</label>
        <picklist>
            <picklistValues>
                <fullName>Addendum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCC_Filings__c</fullName>
        <label>UCC Filings:</label>
        <picklist>
            <picklistValues>
                <fullName>Full UCC-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification UCC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCC_Request_Date__c</fullName>
        <label>UCC Request Date:</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Underwriting_Decision__c</fullName>
        <label>Underwriting Decision:</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by Credit Committee with conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined by Credit Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined - Pending Management Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Management Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending management review returned to u/w</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by merchant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by RapidAdvance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescinded by Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled for credit committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Comp. Pay Off too High - Reconsider Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Will Not Reconsider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified - Will Reconsider in the Future</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Underwriting</label>
    <nameField>
        <displayFormat>U# {000000000}</displayFormat>
        <label>Underwriting ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSyncUnderwritingAndOpportunity.cls
/*
Created Date: April 26th, 2010
Developer Name: Ralph Callaway
Case Number: 03461744

Description:
Maintain a one-to-one relationship between the opportunity and underwriting object.

Mirror certain underwriting fields on the opportunity without using formulas

Functional Logic:
Whenever an underwriting is created, populate the underwriting lookup field on the related Opportunity.

Whenever any of the following underwriting fields change update the corresponding fields on the Opportunity Object:
•   UCC Filings
•   UCC Request Date
•   UCC Filing Reason
•   Decision Date
•   Re-Decision Date
•   Underwriting Decision
*/
/*

Modified
DS-CONAM - 03/04/2015
Version 16 to 32
*/

@isTest
private class TestSyncUnderwritingAndOpportunity {

    private static final Id OPPORTUNITY_ID;
    private static final String TEST_STRING = 'IIEndjPP';
    private static final Date TEST_DATE = System.today();
    private static final DateTime TEST_DATETIME;

    static {
        // decrease precision to avoid issues with rounding on database commit
        TEST_DATETIME = DateTime.newInstance(TEST_DATE.year(), TEST_DATE.month(), TEST_DATE.day());

        // create test opportunity
        Opportunity testOpportunity = new Opportunity(stageName = TEST_STRING, name = TEST_STRING, closeDate = TEST_DATE);
        insert testOpportunity;
        OPPORTUNITY_ID = testOpportunity.id;
    }

    static testMethod void testInsert() {

        Test.startTest();
        // insert a new underwriting
        try {

            CALC.ApexTesting();
            Underwriting__c testUnderwriting = getTestUnderwriting();
            insert testUnderwriting;
        } 
        catch (Exception e) {
            System.assert(e.getMessage().contains('REQUIRED_FIELD_MISSING'), 'Code Failure: Opportunity not linked to underwriting on underwriting creation');
        }
        Test.stopTest();
    }

    static testMethod void testUpdate() {
        // insert a new underwriting
        Test.startTest();
        CALC.ApexTesting();
        Underwriting__c testUnderwriting;
        try {

            CALC.ApexTesting();
            testUnderwriting = getTestUnderwriting();
            insert testUnderwriting;
        } 
        catch (Exception e) {
            System.assert(e.getMessage().contains('REQUIRED_FIELD_MISSING'), 'Code Failure: Opportunity not linked to underwriting on underwriting creation');

        }

        // add fields that need to get synced with opportunity
        testUnderwriting.ucc_filings__c = TEST_STRING;
        testUnderwriting.UCC_Request_Date__c = TEST_DATE;
        testUnderwriting.ucc_filing_reason__c = TEST_STRING;
        testUnderwriting.decision_date__c = TEST_DATETIME;
        testUnderwriting.Underwriting_Decision__c = TEST_STRING;
        testUnderwriting.Re_decision_date__c = TEST_DATETIME;

        // update underwriting

        update testUnderwriting;


        // verify fields are copied over to the opportunity
        Opportunity testOpportunity = [SELECT 
                                           underwriting__c, ucc_filing__c, UCC_Date__c, ucc_filing_reason__c,
                                           Re_Decision_Date__c, Decision_Date__c, Underwriting_Approval__c
                                       FROM 
                                            Opportunity 
                                       WHERE 
                                            id = : OPPORTUNITY_ID];
                                       
        system.assert(testOpportunity.ucc_filing__c == testUnderwriting.ucc_filings__c,
            'Code Failure: UCC Filings not synced to opportunity when underwriting update. Expected: ' + testUnderwriting.ucc_filings__c + ', Found: ' + testOpportunity.ucc_filing__c);
        system.assert(testOpportunity.UCC_Date__c == testUnderwriting.UCC_Request_Date__c,
            'Code Failure: UCC Request Date not synced to opportunity when underwriting update. Expected: ' + testUnderwriting.UCC_Request_Date__c + ', Found: ' + testOpportunity.UCC_Date__c);
        system.assert(testOpportunity.ucc_filing_reason__c == testUnderwriting.ucc_filing_reason__c,
            'Code Failure: UCC Filing Reason not synced to opportunity when underwriting update. Expected: ' + testUnderwriting.ucc_filing_reason__c + ', Found: ' + testOpportunity.ucc_filing_reason__c);
        system.assert(testOpportunity.Decision_Date__c == testUnderwriting.decision_date__c,
            'Code Failure: Decision Date not synced to opportunity when underwriting update. Expected: ' + testUnderwriting.decision_date__c.getTime() + ', Found: ' + testOpportunity.Decision_Date__c.getTime());
        system.assert(testOpportunity.Underwriting_Approval__c == testUnderwriting.Underwriting_Decision__c,
            'Code Failure: Underwriting Decision not synced to opportunity when underwriting update. Expected: ' + testUnderwriting.Underwriting_Decision__c + ', Found: ' + testOpportunity.Underwriting_Approval__c);
        system.assert(testOpportunity.Re_Decision_Date__c == testUnderwriting.Re_decision_date__c,
            'Code Failure: Re-Decision Date not synced to opportunity when underwriting update. Expected: ' + testUnderwriting.Re_decision_date__c + ', Found: ' + testOpportunity.Re_Decision_Date__c);

        Test.stopTest();
    }

    private static Underwriting__c getTestUnderwriting() {
        return new Underwriting__c(opportunity__c = OPPORTUNITY_ID);
    }
}