src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Does_the_Merchant__c</fullName>
        <label>Does the Merchant</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Number_For_Funding__c</fullName>
        <label>Wire Bank Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressOnCheckIf_no_please_explain__c</fullName>
        <label>If, no please explain</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address_on_Check_Match_Bank_Statement__c</fullName>
        <label>Address on Check Match Bank Statement</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Address_on_Check_Match_FRSA__c</fullName>
        <label>Address on Check Match FRSA</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Applicant_2_FICO__c</fullName>
        <label>Applicant #2 FICO</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Are_there_any_Competitor_Debits__c</fullName>
        <description>Do the Bank Statements reference any Competitor Debits or Deposits? YES OR NO 
If, yes please explain</description>
        <label>Are there any Competitor Transactions?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Are_there_any_Odd_Large_Deposits__c</fullName>
        <description>Do the Bank Statements reference any Odd Large Deposits or Transfers? YES OR NO 
If, yes please explain</description>
        <label>Are there Odd Big Deposits or Transfers?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Are_there_special_wiring_instructions__c</fullName>
        <label>Are there special wiring instructions?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bank_Statement_LegalDBA_Voided_Check__c</fullName>
        <description>Does Legal/DBA Name on Bank Statements match Voided Check? YES OR NO
If not, then please address.</description>
        <inlineHelpText>Does Legal/DBA Name on Bank Statements match Voided Check? YES OR NO
If not, then please address.</inlineHelpText>
        <label>Bank Statement Legal/DBA Match Check?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bank_Statement_Legal_DBA_FRSA__c</fullName>
        <description>Does the Legal/DBA Name on the Bank Statements match FRSA? YES OR NO 
If not, then please address .</description>
        <inlineHelpText>Does the Legal/DBA Name on the Bank Statements match FRSA? YES OR NO 
If not, then please address .</inlineHelpText>
        <label>Bank Statement Legal/DBA Match FRSA?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_name_check_match_contract__c</fullName>
        <label>Business name on check match contract</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Called_Confirmed_Contact_Email__c</fullName>
        <label>Called Confirmed Contact Email</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_Add_l_Signer_Mobile_Number__c</fullName>
        <label>Confirmed Add&apos;l Signer Mobile Number</label>
        <picklist>
            <picklistValues>
                <fullName>No Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Under Merchant Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed w/o Merchant name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_Add_l_Signer_Phone_Number__c</fullName>
        <label>Confirmed Add&apos;l Signer Phone Number</label>
        <picklist>
            <picklistValues>
                <fullName>No Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Under Merchant Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed w/o Merchant name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_Contact_Mobile_Number__c</fullName>
        <label>Confirmed Contact Mobile Number</label>
        <picklist>
            <picklistValues>
                <fullName>No Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Under Merchant Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed w/o Merchant name</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_Contact_Phone_Number__c</fullName>
        <label>Confirmed Contact Phone Number</label>
        <picklist>
            <picklistValues>
                <fullName>No Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Under Merchant Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed w/o Merchant name</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_Information_From_QC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed Information From QC:</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Confirmed_additional_signer_fax_number__c</fullName>
        <label>Confirmed additional signer fax number?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_additional_signer_phone_s__c</fullName>
        <label>Confirmed additional signer phone #s?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_primary_signer_e_mail__c</fullName>
        <label>Confirmed primary signer e-mail?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_primary_signer_fax_number__c</fullName>
        <label>Confirmed primary signer fax number?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Does_the_Merchant__c</fullName>
        <label>Does the Merchant Own Their Home</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_value_confirmed_through__c</fullName>
        <label>Home value confirmed through:</label>
        <picklist>
            <picklistValues>
                <fullName>Zillow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trulia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Result Found</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Individual_Bankruptcies_Additional_Notes__c</fullName>
        <label>Individual Bankruptcies Additional Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Individual_Bankruptcies__c</fullName>
        <label>Bankruptcy Filings In The Last Year:</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Judgements_Open__c</fullName>
        <label>Judgements Open</label>
        <picklist>
            <picklistValues>
                <fullName>$5k-$15k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$15-$30k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$30k-$50k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50k and up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mortgage_Delinquent__c</fullName>
        <label>Mortgage Delinquent</label>
        <picklist>
            <picklistValues>
                <fullName>30 DPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 DPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 DPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120 DPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150 DPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180 DPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FORECLOSURE &lt; 1 YEAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FORECLOSURE STARTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MODIFICATION AGREEMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Previous_Applicant_2_FICO__c</fullName>
        <label>Previous Applicant #2 FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_FICO__c</fullName>
        <label>Previous Applicant #1 FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Routing_Number__c</fullName>
        <label>Wire Bank Routing Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Liens_Open__c</fullName>
        <label>Tax Liens Open</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$1-$25k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25k-$50k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50k-75k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$75k and Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>What_is_the_value_of_their_home__c</fullName>
        <label>What is the value of their home?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>What_is_their_home_mortgage_balance__c</fullName>
        <label>What is their home mortgage balance?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ApplicantCredit_Ctrl.cls
public class ApplicantCredit_Ctrl {

	public Opportunity oppRecord{get; set;}
     public Contact conRecord{get; set;}
     public Contact pricipal1Record{get; set;}
     public Contact pricipal2Record{get; set;}
     public Decimal applicant1FICO{get; private set;}
     public Decimal applicant1PrevFICO{get; private set;}
     public String creditBureauSummary{get; private set;}
     public String equityInHome{get; private set;}

	public ApplicantCredit_Ctrl() {
		String oppId = ApexPages.currentPage().getParameters().get('Id');
		conRecord = new Contact();

		if (oppId != null && oppId.trim() != '') {
			List<Opportunity> oppList = [SELECT 
												Id, AccountId, Confirmed_Contact_Phone_Number__c, 
												Confirmed_Contact_Mobile_Number__c, Confirmed_Add_l_Signer_Phone_Number__c,
											    Confirmed_Add_l_Signer_Mobile_Number__c, Mortgage_Delinquent__c, 
											    Tax_Liens_Open__c, Judgements_Open__c, Individual_Bankruptcies__c, 
											    Individual_Bankruptcies_Additional_Notes__c,
												//Does_the_Merchant_Own_Their_Home__c, 
												Does_the_Merchant__c, What_is_the_value_of_their_home__c,
												Home_value_confirmed_through__c, What_is_their_home_mortgage_balance__c,
												Are_there_any_Odd_Large_Deposits__c, Are_there_any_Competitor_Debits__c,
												Bank_Statement_LegalDBA_Voided_Check__c, Bank_Statement_Legal_DBA_FRSA__c,
												Bank_Name__c, Account_Number_For_Funding__c, Routing_Number__c,
												Business_name_check_match_contract__c, Are_there_special_wiring_instructions__c,
												Previous_FICO__c, Previous_Applicant_2_FICO__c, Confirmed_Information_From_QC__c,
												Address_on_Check_Match_FRSA__c, Address_on_Check_Match_Bank_Statement__c,
												AddressOnCheckIf_no_please_explain__c, Called_Confirmed_Contact_Email__c,
												Confirmed_primary_signer_fax_number__c, Confirmed_primary_signer_e_mail__c,
												Confirmed_additional_signer_phone_s__c, Confirmed_additional_signer_fax_number__c,
												Confirmed_additional_signer_e_mail__c, CRR__c, Contact__c, Applicant_2_FICO__c,
												Previous_Opportunity__r.Applicant_2_FICO__c, Sales_Check_List_Notes__c,
												Contact__r.Name, ContactID__c, Eligible_Photo_ID__c, SA_Internal_Notes__c,
												Manual_Applicant_1_FICO_Score__c, Manual_Applicant_2_FICO_Score__c,
												Sales_Note_to_UW_Processing__c
											FROM 
												Opportunity 
											WHERE 
												Id = : oppId LIMIT 1];

			if (!oppList.isEmpty()) {
				oppRecord = oppList.get(0);
				Map<ID, String> contactRoleMap = new Map <ID, String> ();
				Set<String> roleSet = new Set<String> ();

				List<OpportunityContactRole> oppRoleList = [SELECT 
																	ContactId, Role 
																FROM
																	OpportunityContactRole 
																WHERE 
																	OpportunityId = : oppRecord.Id
																	AND Contact.IsDeleted = false
																	AND(Role = 'Principal 1'
																	or Role = 'Principal 2')];


				for (OpportunityContactRole opprole: oppRoleList) {
					if ((!roleSet.contains(opprole.Role)) && (!contactRoleMap.containsKey(opprole.ContactId))) {
						contactRoleMap.put(opprole.ContactId, opprole.Role);
						roleSet.add(opprole.Role);
					}
				}

				if (!contactRoleMap.IsEmpty()) {

					List<Contact> contactList = [SELECT 
														c.Id, c.Name, c.ContactID__c, c.AccountId,
														c.Principal_Home_Phone__c,
														c.Principal_2_Mobile__c, c.OwnershipPercentage__c,
														c.MobilePhone, c.MailingStreet,
														c.MailingState, c.MailingPostalCode,
														c.MailingCity, c.Fax, c.Email, c.Date_of_Birth__c
													FROM 
														Contact c 
													WHERE 
														Id IN: contactRoleMap.keySet()];
					if (!contactList.isEmpty()) {
						for (Contact c: contactList) {
							if (contactRoleMap.get(c.Id) == 'Principal 1') {
                                System.debug('========== contactRoleMap.get(c.Id) ' +contactRoleMap.get(c.Id));
                               
								pricipal1Record = c;
							} else if (contactRoleMap.get(c.Id) == 'Principal 2') {
								pricipal2Record = c;
							}
						}
					}
				}

				applicant1FICO = FormulaFieldUtility.ccApplicant1FICO;
				applicant1PrevFICO = FormulaFieldUtility.applicant1PrevFICO;
				creditBureauSummary = FormulaFieldUtility.creditBureauSummary;
				equityInHome = FormulaFieldUtility.equityInHome;
			}
		} else {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Id Does not Exist!'));
		}
	}

	public PageReference doSave() {

		try {
			/* if(conRecord != null && conRecord.AccountId == null) {
                conRecord.AccountId = oppRecord.AccountId;  
            }
            System.debug('>>>>' + conRecord.Principal_2_First_Name__c);
            upsert conRecord;  
            
            if(conRecord.Id != null && oppRecord.Contact__c == null) {
                oppRecord.Contact__c = conRecord.Id;   
            }*/
			if(oppRecord != NULL){
				upsert oppRecord;
			}
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm, 'Applicant & Credit Information Saved Successfully!'));
		} catch (Exception e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
		}
		return null;
	}

}