src/objects/Five9Task2LeadMappings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Mapping of Five9 Dispositions to Lead Statuses for use in Five9Task2Lead.trigger are persisted here.</description>
    <fields>
        <fullName>Five9Disposition__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Represents a disposition as configured in Five9 and stored in the CallDisposition field on the activity task object.</description>
        <label>Five9Disposition</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LeadStatus__c</fullName>
        <description>Represents a Lead.status as mapped from a Five9 Call disposition</description>
        <label>LeadStatus</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnqualifiedReason__c</fullName>
        <label>Unqualified Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Five9 Call Activity to Lead Mappings</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Five9_Call_Counter__c</fullName>
        <label>Five9 Call Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unqualified_Reason__c</fullName>
        <label>Unqualified Reason</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Business Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business for Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Balance Too High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does not accept Visa/Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Based Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet Only Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than 1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than 9 months lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less then $2,500 V/MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Enough Monthly Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not the Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prohibited Business Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential Phone Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start Up Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Unqualified_Reason__c</fullName>
        <description>When adding a new value, add same in UW object.</description>
        <label>Unqualified Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Adverse Filing - High Competitor Balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adverse Filing - Multiple Stacking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adverse Filing - Open Tax Liens w/o plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bus - Extreme Seasonality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp. Filing - Not in Good Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Processing &lt;$2500/mo.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Processing &lt;$3500/mo.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit - New Multiple BK Filings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit - Significant Credit Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DNR - Willing to reconsider per Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview - Unfavorable Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Drop in CC Sales MoM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Drop in CC Sales YoY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - High Risk Tender Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Loan deal &gt;5 unpaid NSFs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Net Amount too Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under performance month over month</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TaskTriggerhandlerCls.cls
public with sharing class TaskTriggerhandlerCls {

    public static Boolean runOnce = false;
    List < Five9Task2LeadMappings__c > mappings = Five9Task2LeadMappings__c.getAll().values();
    Map < String, String > statusMap = new Map < String, String > ();
    Map < String, String > unqualifiedReasons = new Map < String, String > ();
    Map < String, String > leadCallDispositionMap = new Map < String, String > ();
    List < Lead > leads = new List < Lead > ();
    // Set<Lead> leadSet = new Set<Lead>();
    List < Id > leadId = new List < Id > ();

    Map < Id, Lead > mapLead = new Map < Id, Lead > ();
    String unqualifiedReason;

        public void onAfterInsert(List < Task > taskList) {
            runOnce = true;
            try {
            
            for (Five9Task2LeadMappings__c m: mappings) {

                statusMap.put(m.Five9Disposition__c, m.LeadStatus__c);
                if (m.UnqualifiedReason__c != null) {
                    unqualifiedReasons.put(m.Five9Disposition__c, m.UnqualifiedReason__c);
                }
            }
            system.debug(' statusMap ' + statusMap);
            system.debug(' mappings ' + mappings);

            Set < ID > lListTemp = new Set < Id > ();

            for (Task t: taskList) {

                if (t.WhoId != null && t.WhoId.getSobjectType() == Schema.Lead.sObjectType) {
                    //Lead l = new Lead(Id=t.WhoId); 
                    lListTemp.add(t.WhoId);
                }
            }


            Map < Id, AggregateResult > numTasks = new Map < id, AggregateResult > ([SELECT whoid Id, COUNT(Id) CallCount
            FROM Task WHERE Five9__Five9CallType__c IN('Agent', 'Preview', 'Outbound')
            and who.Id in : lListTemp group by whoid]);
            for (Task t: taskList) {
                //On insert we need to update the status
                if (t.WhoId != null && t.WhoId.getSobjectType() == Schema.Lead.sObjectType) {
                    Lead l = new Lead(Id = t.WhoId);

                    String newStatus = statusMap.get(t.CallDisposition);

                    System.debug('newStatus ' + newStatus);
                    System.debug('t.CallDisposition ' + t.CallDisposition);

                    if (newStatus != null) {
                        l.Status = newStatus;
                        unqualifiedReason = unqualifiedReasons.get(t.CallDisposition);
                        if (unqualifiedReason != null) {
                            l.Unqualified_Reason__c = unqualifiedReason;
                        }

                    }

                    System.debug(' numTasks ' + numTasks);

                    Integer count = numTasks.size() == 0 ? 0 : Integer.valueOf(String.valueOf(numTasks.get(l.id).get('CallCount')));
                    l.Five9_Call_Counter__c = count;
                    mapLead.put(l.id, l);
                }
            }
            if (mapLead.size() > 0) {
                for (Id iTemp: mapLead.keyset())
                leads.add(mapLead.get(iTemp));
                update leads;
            }
            }
            catch (Exception e) {
                System.debug('An exception has been generated ' + e.getMessage() + ' ' + e.getLineNumber());
            }
            
        }

        public void onAfterUpdate(List < Task > newtask1List, Map<Id, Task> oldtasklist) {
            runOnce = true;
            for (Five9Task2LeadMappings__c m: mappings) {

                statusMap.put(m.Five9Disposition__c, m.LeadStatus__c);
                if (m.UnqualifiedReason__c != null) {
                    unqualifiedReasons.put(m.Five9Disposition__c, m.UnqualifiedReason__c);
                }
            }
            for (Task t: newtask1List) {
                if (t.WhoId != null && t.WhoId.getSobjectType() == Schema.Lead.sObjectType) {
                    if (oldtasklist.get(t.Id).CallDisposition != t.CallDisposition) {
                        leadId.add(t.whoID);
                        leadCallDispositionMap.put(t.whoID, t.CallDisposition);
                    }
                }
            }

            //System.debug('leadCallDispositionMap '+leadCallDispositionMap);

            if (leadId.size() > 0) {
                List < Lead > lList = [select id, status, Unqualified_Reason__c from lead where id in : leadId];

                Map < Id, AggregateResult > numTasks = new Map < id, AggregateResult > ([SELECT whoid Id, COUNT(Id) CallCount
                FROM Task WHERE Five9__Five9CallType__c IN('Agent', 'Preview', 'Outbound')
                and who.Id in : LeadID group by whoid]);

                //System.debug(' numTasks  ' +numTasks);

                for (Lead lTemp: lList) {
                    lTemp.Status = statusMap.get(leadCallDispositionMap.get(lTemp.id));
                    //System.debug('lTemp.Status '+lTemp.Status);
                    unqualifiedReason = unqualifiedReasons.get(leadCallDispositionMap.get(lTemp.id));
                    if (unqualifiedReason != null) {
                        lTemp.Unqualified_Reason__c = unqualifiedReasons.get(leadCallDispositionMap.get(lTemp.id));

                    }
                    Integer count = numTasks.size() == 0 ? 0 : Integer.valueOf(String.valueOf(numTasks.get(lTemp.id).get('CallCount')));
                    lTemp.Five9_Call_Counter__c = count;
                    leads.add(lTemp);
                }
            }

            if (leads.size() > 0) update leads;
        }
        
        public void onAfterDelete(List < Task > newtask1List, List<Task> oldtasklist) {
        runOnce = true;
        
        try{
        leads = new List < Lead > ();
        for (Five9Task2LeadMappings__c m: mappings) {

                statusMap.put(m.Five9Disposition__c, m.LeadStatus__c);
                if (m.UnqualifiedReason__c != null) {
                    unqualifiedReasons.put(m.Five9Disposition__c, m.UnqualifiedReason__c);
                }
            }
        
        for (Task t: oldtasklist) {
            if (t.WhoId != null && t.WhoId.getSobjectType() == Schema.Lead.sObjectType) {
                leadID.add(t.WhoId);
            }
        }

        if (leadId.size() > 0) {
            List < Lead > lList = [select id, status, Unqualified_Reason__c from lead where id in : leadId];
            Map < Id, AggregateResult > numTasks = new Map < id, AggregateResult > ([SELECT whoid Id, COUNT(Id) CallCount
            FROM Task WHERE Five9__Five9CallType__c IN('Agent', 'Preview', 'Outbound')
            and who.Id in : LeadID group by whoid]);

            for (Lead lTemp: lList) {
                Integer count = numTasks.size() == 0 ? 0 : Integer.valueOf(String.valueOf(numTasks.get(lTemp.id).get('CallCount')));
                lTemp.Five9_Call_Counter__c = count;
                leads.add(lTemp);
            }
        }

        if (leads.size() > 0) {
            update leads;
        }


    }
    catch (Exception e) {
        System.debug('An exception has been generated ' + e.getMessage() + ' ' + e.getLineNumber());
    }

    }
    
       public static void Queue_TaskAfterInsert(List < Task > newtask1List) {
    // Trigger to create/update the relevant Priority Queue object following Lead insert/modification
   List<Lead>        toSyncLead = new List<Lead>();
   List<Opportunity> toSyncOpp  = new List<Opportunity>();
   Set<Id> fetchLead = new Set<Id>();
   Set<Id> fetchOpp  = new Set<Id>();

   for (Task t : newtask1List) {
      String potentialOppId = t.WhatId;
      if      (t.WhatId != NULL && potentialOppId.substring(0, 3) == '006') { fetchOpp.add(t.WhatId); }
      else if (t.WhoId != NULL && t.WhatId == NULL)                         { fetchLead.add(t.WhoId); }
   }   // end for Task loop

   Boolean success;
   if (fetchLead.size() > 0) {
      toSyncLead = [SELECT Id,Company,status,ConvertedOpportunityId FROM Lead WHERE Id IN: fetchLead];
      success = Queue_Sync.syncQueue(toSyncLead);   // Add try/except
   }
   if (fetchOpp.size() > 0) {
      toSyncOpp = [SELECT Id,Name FROM Opportunity WHERE Id IN: fetchOpp];
      success = Queue_Sync.syncQueue(toSyncOpp);   // Add try/except   
   }
   }
}