src/objects/Green_Tree_Oppy_Extension__c.object
<CustomObject>
    <description>This object has been created to capture the required field details for Green Tree Opportunity and is a related child record of opportunity used only in the case of opportunity records having record type as -Green Tree.</description>
    <fields>
        <fullName>Advance_Payoff_Date__c</fullName>
        <label>Advance Payoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Average_CC_Sales__c</fullName>
        <label>Average CC Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Gross_Sales__c</fullName>
        <label>Average Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Payment_Amount__c</fullName>
        <label>Daily Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Balance__c</fullName>
        <description>NO FORMULA AS OF NOW</description>
        <formula>0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Days_to_Repay__c</fullName>
        <formula>No_of_Payments__c/5*7</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Days to Repay</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Payments__c</fullName>
        <label># of Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Green_Tree</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductTerm__c</fullName>
        <label>Term</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Green Tree Oppy Extension</label>
    <nameField>
        <displayFormat>G{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Green Tree Oppy Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OppGreenTreeViewController1.cls
public class OppGreenTreeViewController1{
  
    public String iTemp{get;set;}
    public Green_Tree_Oppy_Extension__c gtNew{get;set;}
    public Boolean isEdit{get;set;}
    
 // private Apexpages.StandardController controller; 

     
    public PageReference DoSave() {
    
    // this.controller.save();
    
     PageReference newPage = New PageReference('/apex/SplashGreenTree');
     newPage.setRedirect(true);
     return newPage;
    try {
  upsert gtNew;
    }
catch (System.QueryException e) {
  System.debug('caught Exp!');
}
    return null;
    }
    public PageReference Cancel(){
    PageReference pageRef= new PageReference('/apex/SplashGreenTree');
    pageRef.setredirect(true);
    return pageRef;
    }  
    
    
       public OppGreenTreeViewController1(ApexPages.StandardController controller)
    {
        isEdit=false;
        
        this.iTemp=controller.getId();
        System.debug('itemp '+ itemp);
        
       list<Green_Tree_Oppy_Extension__c>GTM=[select
                        No_of_Payments__c,Advance_Payoff_Date__c,Average_CC_Sales__c,
                        Average_Gross_Sales__c,Daily_Payment_Amount__c,Estimated_Balance__c,
                        Estimated_Days_to_Repay__c,Id,IsDeleted,LastActivityDate,LastModifiedById,
                        LastModifiedDate,Name,Opportunity__c,Product__c,ProductTerm__c
                        FROM 
                        Green_Tree_Oppy_Extension__c limit 1
                   ];
                this.gtNew=GTM[0]; 
        
    }
    public Pagereference edit(){
        isEdit = true;
        return null;
    }  
    

}