src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BA_X2_years_in_business__c</fullName>
        <label>&lt; 2 years in business</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Balance_Sheet__c</fullName>
        <label>Current Balance Sheet</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EC_Criteria_Decision__c</fullName>
        <formula>if(ispickval( Product__c, &quot;MCA&quot;),If ( ISPICKVAL( EC_X4_consecutive_months_of_processing__c , &quot;Yes&quot;) , &quot;INELIGIBLE - STOP RIGHT NOW&quot;,If ( ISPICKVAL( EC_X12_separate_daily_deposits_per_month__c , &quot;Yes&quot;) , &quot;INELIGIBLE - STOP RIGHT NOW&quot;, If ( ISPICKVAL(  EC_Company_in_business_6_months__c  , &quot;Yes&quot;) , &quot;INELIGIBLE - STOP RIGHT NOW&quot;,
&quot;Eligible Criteria Met&quot; ))),if(ispickval( Product__c, &quot;Loan&quot;),If ( ISPICKVAL(  EC_Company_in_business_6_months__c  , &quot;Yes&quot;) , &quot;INELIGIBLE - STOP RIGHT NOW&quot;,&quot;Eligible Criteria Met&quot; ),&quot;Eligible Criteria Met&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Criteria Decision</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_X12_separate_daily_deposits_per_month__c</fullName>
        <label>&lt; 12 separate daily deposits per month</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EC_X4_consecutive_months_of_processing__c</fullName>
        <label>&lt; 4 consecutive months of processing</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X4_consecutive_months_of_Bank_Statements__c</fullName>
        <label>&lt;4 consecutive months of Bank Statements</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A MCA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Eligibility_Criteria_Ctrl.cls
public with sharing class Eligibility_Criteria_Ctrl {

public Opportunity oppRecord{get; set;}
     
     public Eligibility_Criteria_Ctrl(){
         String oppId = ApexPages.currentPage().getParameters().get('Id');
        
        if (oppId != null && oppId.trim() != ''){
            List<Opportunity> oppList = [SELECT
            									Id,EC_X4_consecutive_months_of_processing__c, X4_consecutive_months_of_Bank_Statements__c, 
                                         		Current_Balance_Sheet__c,EC_X12_separate_daily_deposits_per_month__c,
                                         		BA_X2_years_in_business__c,EC_Criteria_Decision__c
                                         FROM 	
                                         		Opportunity 
                                         WHERE	
                                         		Id = :oppId LIMIT 1];
                                            
            if (!oppList.isEmpty()) {
                oppRecord = oppList.get(0); 
            }
        }else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Id Does not Exist!'));   
        }    
    }
    
    public PageReference doSave() {
           
        try{
            upsert oppRecord;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Eligibility Criteria Information Saved Successfully!'));
        }catch(Exception e){

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }
        return null;
    } 
}