src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>QC in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Offer Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documents Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer Rescinded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted For Funding Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OppOppDocUpdateStatus.cls
/**
 *********************************************************************************************************************
 * Module Name   : OppOppDocUpdateStatus for Biz2Credit Webservice
 * Description   : Update status for Opportunity and Oppr_Documents
 * Throws        : <Any Exceptions/messages thrown by this class/triggers>
 * Calls         : <Any classes/utilities called by this class | None if it does not call>
 * Test Class    :
 *
 * Organization  : Rainmaker Associates LLC
 * @RestResource(urlMapping='/rest/SubmitApplication/*')
 * Revision History:-
 * Version  Date           Author           WO#         Description of Action
 * 1.0      01/11/2012     Milligan                      Initial Version
 *
 *******************************************************************************************************************
 **/
public with sharing class OppOppDocUpdateStatus {

	public static void updateFromOppDocument(List <Oppr_Document__c> odc) {

		List <String> oppsToSearch = new List <String> ();

		for (Oppr_Document__c oppDoc: odc) {
			//Get all the opportunities
			oppsToSearch.add(oppDoc.opportunity__c);
		}

		updateOppStatusToContractAvailable(oppsToSearch);

	}

	public static void updateFromOpp(List <String> oppsToSearch) {

		updateOppStatusToContractAvailable(oppsToSearch);
	}

	//Rule 7 Changing from "Reviewing Documents" to "Contract Available"
	//If the Contract Document is available and attached to the Opportunity Documents, the status of the Application/Opportunity 
	//should changed to be "Contract Available"
	public static void updateOppStatusToContractAvailable(List <String> oppIds) {

		List <Oppr_Document__c> oppContractDocs = new List <Oppr_Document__c> ();

		oppContractDocs = [SELECT
						   	id, status__c, opportunity__c, opportunity__r.Status__c
						   FROM
							Oppr_Document__c
						   WHERE
							opportunity__r.Status__c = 'Reviewing Documents'
						   AND
							document_name__c = 'Contract'
						   AND
							opportunity__c IN: oppIds];

		if (!oppContractDocs.IsEmpty()) {

			List <Opportunity> oppToUpdate = new List <Opportunity> ();
			List <String> oppIdsToSearch = new List <String> ();
			List <String> oppDocIds = new List <String> ();
			Map <String, String> attachmentMap = new Map <String, String> ();

			// Loop thru docs that are Contract Documents and opportunity status is reviewing document
			// add opportunity doc  id  to list to retrieve attachments
			for (Oppr_Document__c odc: oppContractDocs) {
				oppDocIds.add(odc.id);
			}

			/*List<Attachment> attachmentList = new List<Attachment>([SELECT ParentID, name FROM Attachment WHERE  parentID IN : oppDocIds]);
        
            for(Attachment at: attachmentList){
            
                attachmentMap.put(at.parentId, at.name);    
            }
     */
			// loop the contract docs and see if attachment is available
			// add the opportunity id to the list of opportunities to update
			for (Oppr_Document__c odc: oppContractDocs) {

				//if(attachmentMap.containsKey(odc.id)){
				oppIdsToSearch.add(odc.opportunity__c);
				// }               
			}
			//if there are opportunities with status = 'Reviewing Documents' to update get them update status
			if (!oppIdsToSearch.IsEmpty()) {

				oppToUpdate = [SELECT id, status__c FROM Opportunity WHERE id IN: oppIdsToSearch];

				if (!oppToUpdate.IsEmpty()) {

					for (Opportunity opp: oppToUpdate) {
						opp.status__c = 'Contract Available';
					}

					update oppToUpdate;
				}
			}

		} //oppContractDocs.IsEmpty()

	}
}