src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System</description>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSendDocuments.cls
@isTest 
public class TestSendDocuments {

   static testMethod void testSendDocumentsMethod() {
    
        Test.startTest();
        CALC.ApexTesting();
        Opportunity opp = Biz2CreditUtils.createOpportunity();
        Oppr_Document__c OppDoc = Biz2CreditUtils.createOppDoc(opp);
        Attachment att = Biz2CreditUtils.createAttachment(OppDoc);
        // request 1 
        sendDocuments.sendDocuments(opp.External_ID__c, opp.Source_System__c, att.Id, att.Name, att.Body, 'txt');
        // request 2
        sendDocuments.sendDocuments(opp.External_ID__c, '', att.Id, att.Name, att.Body, 'txt');
        Test.stopTest();
   }
}