src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Processing_Error_Date__c</fullName>
        <label>Processing Error Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Representative__c</fullName>
        <description>What RapidAdvance Processing Rep has this account?</description>
        <label>Processing Representative</label>
        <picklist>
            <picklistValues>
                <fullName>Amanda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atiya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cassandra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Katara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tina</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Employee__c</fullName>
        <label>Risk Employee</label>
        <picklist>
            <picklistValues>
                <fullName>Deborah Oliver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gil Bowen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marlowe Rogers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tony Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vanessa Waller</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send_Risk_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fires off a workflow to send an Email notification</description>
        <label>Send Risk Alert</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User_Lookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Quick reference list of emails associated with particular strings, for conversion from Picklist values.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>User Lookup</label>
</CustomObject>

src/classes/RiskAlert_Test.cls
@isTest

private class RiskAlert_Test {

	static testMethod void testRiskAlert() {
		CALC.ApexTesting(); // Set test mode for the CALC class

		// Insert test data into the User Lookup Custom Setting
		User_Lookup__c test1 = new User_Lookup__c(Name = 'test1', Email__c = 'test@test.com');
		insert test1;
		User_Lookup__c test2 = new User_Lookup__c(Name = 'test2', Email__c = 'test2@test.com');
		insert test2;

		Opportunity o = new Opportunity();
		o.Name = 'Test Opp';
		o.StageName = 'NO Contact Made';
		o.CloseDate = Date.today();
		Database.SaveResult sr = Database.insert(o);

		String oppId = sr.GetId();
		o.Processing_Error_Date__c = Datetime.NOW();
		o.Processing_Representative__c = 'test1';
		o.Risk_Employee__c = 'test2';
		update o;

		Opportunity[] o_query = [SELECT
		Id, Send_Risk_Alert__c
		FROM
		Opportunity
		WHERE
		Id = : oppId];
		System.assertEquals(true, o_query[0].Send_Risk_Alert__c);
	}

} // end class