src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_CC_sales_Avg_4_Mo_times_12__c</fullName>
        <label>Annual CC sales (Avg 4 Mo. times 12):</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Gross_sales_Avg_2_Mo_times_12__c</fullName>
        <label>Annual Gross sales (Avg 2 Mo. times 12):</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Bankruptcies__c</fullName>
        <label>Business Bankruptcies:</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Judgements__c</fullName>
        <label>Business Judgements</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$1-$25k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25k-$50k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50k-$75k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$75k and Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Open_Tax_Lien_Amount__c</fullName>
        <label>Lien Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Open_Tax_Lien_Type__c</fullName>
        <label>Business Open Tax Lien Type</label>
        <picklist>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State &amp; Federal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Open_Tax_Liens__c</fullName>
        <label>Business Tax Liens Outstanding</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$1-$25k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25k-$50k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50k-$75k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$75k and Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Status__c</fullName>
        <label>Business Status:</label>
        <picklist>
            <picklistValues>
                <fullName>Dissolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not In good Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delinquent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Tax_Lien_Date_Filed__c</fullName>
        <inlineHelpText>If entering a single date use the format: &quot;MM/DD/YYYY&quot;
If entering multiple dates use a semicolon &apos;;&apos; and a space &apos; &apos; to seperate the dates. E.G.: &quot;MM/DD/YYYY; MM/DD/YYYY; MM/DD/YYYY....&quot;</inlineHelpText>
        <label>Date(s) Lien Filed</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Tax_Lien_Filing_State_s__c</fullName>
        <inlineHelpText>If entering a single state use the abbreviation format: &quot;AK&quot; 
If entering multiple states use a semicolon &apos;;&apos; and a space &apos; &apos; to seperate the states. E.G.: &quot;AK; AL; AR....&quot;</inlineHelpText>
        <label>State(s)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_Business_Ownership_Confirmed__c</fullName>
        <label>Confirmed principal owner(s) in Westlaw?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable To Confirm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirm_DBA_Address_against_Google_Maps__c</fullName>
        <label>Confirm DBA/Address against Google Maps:</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Results</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_Westlaw_real_property_search__c</fullName>
        <label>Confirmed Westlaw real property search</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed w/No Match</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO Result</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_business_DBA_name__c</fullName>
        <label>Confirmed business DBA name?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confirmed_legal_name_in_Westlaw__c</fullName>
        <label>Confirmed legal name in Westlaw?</label>
        <picklist>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Web-Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable To Confirm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Does_Merchant_Own_The_Business_Location__c</fullName>
        <label>Does Merchant Own The Business Location?</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EC_Company_in_business_6_months__c</fullName>
        <label>Company in business &lt; 1 year</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes Starter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Eligible_Photo_ID__c</fullName>
        <label>Eligible Photo ID</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FRSA_legal_name_same_as_in_Salesforce__c</fullName>
        <label>FRSA legal name same as in Salesforce?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>If_no_please_explain_principal_westlaw__c</fullName>
        <label>If no, please explain</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NAMAA__c</fullName>
        <label>NAMAA TAG for Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_UCC_Filings__c</fullName>
        <label>Other UCC Filings:</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Entity__c</fullName>
        <label>Type of Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Liability Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Liability Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable To Confirm by QC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UW_able_to_confirm_Entity_Type__c</fullName>
        <label>UW able to confirm Entity Type</label>
        <picklist>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BusinessReview_Ctrl.cls
public class BusinessReview_Ctrl {

	public Opportunity oppRecord { get; set; }
    public Account accRecord { get; set; }
    public String creditAlert { get; private set; } 
    public String SCFAlert { get; private set; } 
    public String businessCategoryAlert { get; private set; }
    public String businessAlertCount { get; private set; }
    public String criteriaDecision { get; private set; }
    public String isTheBusinessTypeConsideredLuxury { get; private set; }

 
	public BusinessReview_Ctrl() {
		String oppId = ApexPages.CurrentPage().getParameters().get('Id');

		if (oppId != null && oppId.trim() != '') {
			List <Opportunity> oppList = [SELECT 
												Id, Type_of_Entity__c, Business_Status__c, AccountId,
												Confirmed_business_DBA_name__c, Confirmed_legal_name_in_Westlaw__c,
												If_no_please_explain_principal_westlaw__c,
												CH_Business_Ownership_Confirmed__c, NAMAA__c,
												Eligible_Photo_ID__c, Other_UCC_Filings__c,
												Confirmed_Westlaw_real_property_search__c,
												Does_Merchant_Own_The_Business_Location__c,
												Confirm_DBA_Address_against_Google_Maps__c,
												FRSA_legal_name_same_as_in_Salesforce__c,
												Business_Judgements__c, EC_Company_in_business_6_months__c,
												Business_Open_Tax_Lien_Amount__c,
												Business_Tax_Lien_Date_Filed__c, Business_Open_Tax_Lien_Type__c,
												Business_Tax_Lien_Filing_State_s__c, UW_able_to_confirm_Entity_Type__c,
												Business_Bankruptcies__c, Business_Open_Tax_Liens__c,
												Annual_CC_sales_Avg_4_Mo_times_12__c,
												Annual_Gross_sales_Avg_2_Mo_times_12__c,
												Current_Processor__c, Processor_Name__c,
												Confirmed_Business_Information_from_QC__c,
												Confirmed_FRSA_Dates__c, Average_Ticket__c, Current_Tax_Returns__c, 
												Current_Profit_Loss__c,
												Current_Balance_Sheet__c, X1_Year_Credit_Card_Statement__c,
												X1_Year_Bank_Statements__c, BA_FICO_score_500__c, SIC_CODE__c,
												Business_Category__c, BAM_Match_Selection__c,
												CRR__c, CRR__r.FICO__c,
												EC_X4_consecutive_months_of_processing__c, 
												X4_consecutive_months_of_Bank_Statements__c,
												EC_X12_separate_daily_deposits_per_month__c,
												BA_X2_years_in_business__c,
												EC_Criteria_Decision__c,
												Merchant_Website__c, UWEligible_for_Rapid_Funding__c
											FROM 
												Opportunity 
											WHERE 
												Id = : oppId LIMIT 1];

			if (!oppList.isEmpty()) {
				oppRecord = oppList.get(0);
			}
			// Business Alerts
			creditAlert = FormulaFieldUtility.QCConditionalCriteria;
			SCFAlert = FormulaFieldUtility.QCSCFAlert;
			BusinessCategoryAlert = FormulaFieldUtility.QCBusinessCategoryAlert;
			BusinessAlertCount = FormulaFieldUtility.BABusinessAlertCount;
			CriteriaDecision = FormulaFieldUtility.ECCriteriaDecision;
			isTheBusinessTypeConsideredLuxury = FormulaFieldUtility.BAIsTheBusinessTypeConsideredLuxury;

		} 
		else {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Id Does not Exist!'));
		}
	}

	public PageReference doSave() {

		try {
			if (oppRecord != null) {
				upsert oppRecord;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Business Review Information Saved Successfully!'));
			}
		} 
		catch (Exception e) {

			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
		}
		return null;
	}

}